### ISSUE TITLE
number of running subjobs column stays empty

### ISSUE THREAD

**Issue by pkoppenb** [ganga-devs/ganga#1130]
Dear ganga folks,

In ganga I can do len(jobs(1554).subjobs.select(status="running"))

so I added a column that lists me the number of running subjobs in my monitoring:

'run':'lambda j: len(j.subjobs.select(status="running"))'

but that comes out empty. Am I too ambitious or did I do an obvious mistake?

Thanks

Patrick

**Comment by egede** [comment]
@rob-c Can you have a look at this.

**Comment by rob-c** [comment]
@egede OK I'll see if I get a chance to look at this but I'm a little swamped with other work atm :(

**Comment by mesmith75** [comment]
@pkoppenb These functions end up looking at the XML so `j.subjobs` gives you a `SubjobXMLList` rather than a job registry slice. `SubjobXMLList` has no select method so it returns nothing. If you do something along the lines of:
```python
'lambda j: j.subjobs.getAllSJStatus().count("completed")'
```
you should get what you want. Although this is rather moot with the most recent releases, it might be worth knowing in case you want to do similar things in the future.

**Comment by pkoppenb** [comment]
Thanks. I'll give it a try. How do I understand your last sentence. Should I try it with a future release?

**Comment by mesmith75** [comment]
The current release should have a column showing the number of completed subjobs. The next release (due Monday) will make that more informative: running/failed/completing/completed .
