### ISSUE TITLE
Dirac tags

### ISSUE THREAD

**Issue by afortiorama** [ganga-devs/ganga#1153]
Hi,

Dirac is introducing the concept of tags so that the user can select specific resources like GPU by selecting a tag. Some of the local users using ganga for direct job submission could be redirected to use dirac if it was possible to add the tags to the JDL produced by ganga. Is it something you are already looking into? 

cheers
alessandra

**Comment by mesmith75** [comment]
We haven't looked into it but we certainly should. Do you have an example JDL that we could look at?

The j.backend.settings may be sufficient for it.
Thanks

**Comment by afortiorama** [comment]
the JDL parameter is literally called 'Tags'. So when it is set it should be something like

Tags = "gpus"

I don't know the exact syntax for multiple tags.

cheers
alessandra

**Comment by alexanderrichards** [comment]
Since we don't write the JDL ourselves but rather use the DIRAC API we will need to see what the relevant method for adding this JDL option is.

After a brief look I believe the following is what we need:
[Job.py#707](https://github.com/DIRACGrid/DIRAC/blob/integration/Interfaces/API/Job.py#L707)

As the method name starts set... you should be able to already use this by using the Dirac backend.settings dictionary.

The only proviso is that the DIRAC instance that you are submitting to will have to have this method in their API. Since you say this is a recent addition it may well be that the deployed instances need to be updated before this becomes available. Easiest thing here would be set up your dirac_ui against that instance and try the method interactively at the python interpreter.

**Comment by mesmith75** [comment]
@afortiorama As @alexanderrichards says using
```python
j.backend.settings['Tags'] = ['gpus']
```
Should work for what you want. Could you let us know if it does?

**Comment by mesmith75** [comment]
@afortiorama Is this resolved?
