### ISSUE TITLE
Opening 6.0.44 tasks in 6.1.14 fails

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#123]
A user has reported problems with Ganga 6.1.14 opening the tasks repo from 6.0.44.

```

> Hi all,
>
> I see my beloved 600r44 version of ganga is no longer available as it isn't
> built for x86_64-slc6-gcc49-opt. In 601r14 however, my tasks appear to be
> inaccessible due to the following error:
>
> Ganga In [6]: tasks Ganga.Core.GangaRepository : ERROR XML from-file error
> for file: dictionary changed size during iteration
> Ganga.Core.GangaRepository : ERROR XML File failed to load for Job id: 0
> Ganga.Core.GangaRepository : ERROR Actual Error was: XMLFileError:
> from-file error (<type 'exceptions.RuntimeError'>:dictionary changed size
> during iteration)
> Ganga.Core.GangaRepository : ERROR XML from-file error for file: dictionary
> changed size during iteration
> Ganga.Core.GangaRepository : ERROR XML File failed to load for Job id: 0
> Ganga.Core.GangaRepository : ERROR Actual Error was: XMLFileError:
> from-file error (<type 'exceptions.RuntimeError'>:dictionary changed size
> during iteration)
> Ganga.Core.GangaRepository : ERROR Error Loading Jobs!
> Ganga.Runtime.bootstrap : ERROR Error: RegistryKeyError: Read: The object
> #0 in registry 'tasks' could not be accessed - Repository 'tasks' object #0
> is not accessible because of an XMLFileError: XMLFileError: from-file error
> (<type 'exceptions.RuntimeError'>:dictionary changed size during
> iteration)!
> Ganga Out [6]:
>
> Does anyone know how or if I can recover my tasks?
>
> Thanks,
> Conor
```

**Comment by olupton** [comment]
I'm not sure if this should be a different issue, but I just tried to open my 6.1.13 repository (which contains several LHCbTasks) with 6.1.14 and got several errors:

Ganga.Utility.Config               : ERROR    sanity check failed: defaults_BoxMetadataObject: no makeConfig() found in the code
Traceback (most recent call last):
  File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/bin/ganga", line 61, in <module>
    Ganga.Runtime._prog.new_user_wizard()
  File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/Runtime/bootstrap.py", line 461, in new_user_wizard
    self.rollHistoryForward()
  File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r14/install/ganga/python/Ganga/Runtime/bootstrap.py", line 268, in rollHistoryForward
    with open(versions_filename, 'r') as versions_file:
IOError: [Errno 2] No such file or directory: '/data/lhcb/users/lupton/akepahome/olupton/gangadir61/.used_versions'
Ganga.GPIDev.Lib.Tasks             : ERROR    Unknown/Unexpected Error in starting up tasks main loop
Ganga.GPIDev.Lib.Tasks             : ERROR    Exiting: err='LHCbTask' object has no attribute '_getWriteAccess'

I created an empty file /data/lhcb/users/lupton/akepahome/olupton/gangadir61/.used_versions and then tried again, which gave me:

Ganga.Utility.Config               : ERROR    sanity check failed: defaults_BoxMetadataObject: no makeConfig() found in the code
Ganga.GPIDev.Lib.Tasks             : ERROR    Exiting: err='LHCbTask' object has no attribute '_getWriteAccess'

Ganga In [2]: tasks
Ganga.Core.GangaRepository         : ERROR    XML from-file error for file:
dictionary changed size during iteration
Ganga.Core.GangaRepository         : ERROR    XML File failed to load for Job id: 41
Ganga.Core.GangaRepository         : ERROR    Actual Error was:
XMLFileError: from-file error (<type 'exceptions.RuntimeError'>:dictionary changed size during iteration)
Ganga.Core.GangaRepository         : ERROR    XML from-file error for file:
dictionary changed size during iteration
Ganga.Core.GangaRepository         : ERROR    XML File failed to load for Job id: 41
Ganga.Core.GangaRepository         : ERROR    Actual Error was:
XMLFileError: from-file error (<type 'exceptions.RuntimeError'>:dictionary changed size during iteration)
Ganga.Core.GangaRepository         : ERROR    Error Loading Jobs!
Ganga.Runtime.bootstrap            : ERROR    Error: RegistryKeyError: Read: The object #41 in registry 'tasks' could not be accessed - Repository 'tasks' object #41 is not accessible because of an XMLFileError: XMLFileError: from-file error (<type 'exceptions.RuntimeError'>:dictionary changed size during iteration)!

Rolling back to 6.1.13 still appears to work for the moment (at least I can open the repository and see my jobs/tasks).

**Comment by rob-c** [comment]
@olupton Could you perform a report(jobs(41)) and share the output please, I'm curious what could be causing this problem in loading a task from disk.

**Comment by rob-c** [comment]
I suspect that this has been fixed in #179 as part of looking at #173 There was a bug in the copying of the LHCbDataset which is copied on loading from XML at some stage.
This is difficult to track down/reproduce so I'm going to opt to keep this open as part of the next version distributed to LHCb users.

**Comment by drmarkwslater** [comment]
I would hope this is fixed by several tasks and registry fixes that have gone in. This can probably be closed with 6.1.19 if no-one says otherwise.

**Comment by rob-c** [comment]
This was actually a bug in LHCbDataset which has been 'fixed' for a while but I would still like someone to go away and test that this actually works before we close it.
There have been a __lot__ of changes wrt the Tasks recently and the majority of LHCb users using Tasks will be wanting to migrate from 6.0.44 to a working 6.1.xy build.

**Comment by rob-c** [comment]
I tested this by hand and it seems to be working now
