### ISSUE TITLE
Remote inputfiles and optsfiles not working

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1257]
We need to fix the ability for jobs to have inputfiles or optsfiles as DiracFiles so they get copied to the WN. It doesn't look to be working properly at the moment.

**Comment by rob-c** [comment]
I think the best way of achieving this would be to add something like a `workerDir` parameter to the `DiracFile` class to allow for placing a file into a new relative directory on the WN.

It's still possible to just add the file to a directory within a `.tar` file and upload this with the job. This works as when that is extracted on the WN the file will then be placed in the correct path, but this is a slightly ugly work-around.

I tried a while ago to add this to all `IGangaFile` classes but this required unifying the _put_-like methods into a common API so that a user can sanely request a file be placed in a path whether it's from `MassStorage` or `DIRAC` APIs.

**Comment by mesmith75** [comment]
@rob-c Yes you can just upload it with the job but it would be nice to give `inputfiles` an LFN and have it copy over to the WN. I can envisage people having vast BDT weight files that wouldn't fit into the sandbox.

**Comment by rob-c** [comment]
@mesmith75 The .tar `hack` works with DiracFile if the file is requested as an inputfile, but yes it would be nice to add direct support to the DiracFile so that it respects the placement of the file in the WN.
