### ISSUE TITLE
Change default directory for application check-out

### ISSUE THREAD

**Issue by moredanphysics** [ganga-devs/ganga#1279]
When using "prepareGaudiExec()" the application is always checked out in ~/cmtuser/ which means that, as soon as the action is repeated, Ganga fails as it already has an application.

Would it not make more sense to check out the application in the /tmp/ directory, under a directory with a random (or otherwise unique) name? Alternatively, Ganga should clean up the ~/cmtuser directory after submission, since the user does not care about this checkout out application anyway.

**Comment by mesmith75** [comment]
Using `myPath='/path/to/some/location/of/your/choice'` sets where it gets checked out to. Perhaps we can change the default to `/tmp/user` - I don't think it makes any difference.

With regards cleaning up I'm not sure people will be too impressed with ganga carrying out `rm -rf` commands.

**Comment by egede** [comment]
I guess there are two different use cases here.

1. The checked out area is not really used as the only change is a single options file, potentially located elsewhere.
2. The are has checked out C++ code that the user is developing.

For the first case, the proposal from @DanJohnsonCERN makes sense but not at all for the second case. I suggest to leave things as they are. If you want the expected behaviour, it is trivial to define a small wrapper function in the `~/.ganga.py' file that then automatically will be available each time you start Ganga.

**Comment by moredanphysics** [comment]
Hi all,

Surely if one is using "prepareGaudiExec("DaVinci","v44r3")" (or whatever the exact syntax is I don't remember) one is expecting to get exactly the same code every time. So I'm struggling to understand use-case (2) from Ulrik. 

Isn't it more likely that most people are using this function precisely *because* they aren't developing code, otherwise they'd be using GaudiExec not prepareGaudiExec?

Dan

**Comment by egede** [comment]
@DanJohnsonCERN I believe that it is used once within Ganga (as an interactive command) and not in scripts for every job submitted.

**Comment by moredanphysics** [comment]
I'm not so sure - I think lots of people are using it as recommended here (https://lhcb.github.io/starterkit-lessons/first-analysis-steps/davinci-grid.html) where it just goes instead of "GaudiExec()" in your Ganga script. 

If that's not how prepareGaudiExec() should be used, can I suggest we add something to do it inside a script - i bet many people just want to use the vanilla DaVinci and don't care (or want to know) where it is being checked out. In the most natural case it wouldn't need to be checked out at all...

**Comment by egede** [comment]
Well the same page is discussing using `GaudiExec` just a bit further down so I am not sure about the difference. I would prefer that the users are reusing the same checked out area each time rather than performing a new check-out each time. You suggestion also has several problems.

- Ganga should not automatically delete items which are created by a user action. It gives an unpredictable change of ownership.
- Resubmission will be broken if directory deleted straight afterwards. If just left in `/tmp` it might be deleted by the machine you run on and then give unpredictable results.
- If running on `lxplus` the `/tmp` area is not shared and an auto-resubmit running from a different machine will fail.

**Comment by rob-c** [comment]
I suggested that this page on DaVinci/ganga lessons be re-worded a while ago to avoid this sort of confusion in understanding how this should be used.

In short `prepareGaudiExec()` should only be used once (if required) to get your git based project checked out. It was added to address people wanting to run DaVinci jobs without doing local developments. i.e. submitting with new job opts etc.

GaudiExec is designed to work with a local checkout from `lb-dev` somewhere/anywhere. This is required due to the build target for submitting a job to the grid comes from the lhcb scripts.

Also: `help(prepareGaudiExec)` will let you know what arguments you can pass to it to override the defaults which allows for larger scripts to prepare multiple DaVinci areas in different paths.

If you're using the same `build` of DaVinci everywhere I would suggest using `GaudiExec.prepare` to prepare the application once then submit multiple jobs from this prepared application which should be faster as it saves having to checkout and recompile every single time.

**Comment by moredanphysics** [comment]
Hi @rob-c , @egede , Taking one further step back, why does DaVinci need to be checked out at all? Why can't the grid job just execute "lb-run" somewhere? Or is this an LHCbDirac limitation?

PS: Rob I see you mentioned a complication from the lhcb scripts that I can't say I understand... why does this stop us running lb-run?

**Comment by egede** [comment]
@DanJohnsonCERN That is worth a discussion. Please start a new thread.

**Comment by rob-c** [comment]
Hi again,

OK the job submission broadly has the following constraints:

Ganga doesn't know what (if anything) has been changed in a project.
i.e. Ganga has no way of querying does this LHCb application need to be rebuilt each time.
How should Ganga construct the environment for the job on the worker node?
i.e. How if something has changed should this overload the default components on the worker node.

These 2 problems are solved by the new LHCb build system having a Ganga build target.
This builds all of the required files needed to run a job into 1 `.tar.gz` target file.

This allows Ganga to capture this build-target for an application, arrange for it to be transferred to the worker node, then it additionally provides a consistent entry point which handles all of the environment initialisation within the LHCb build system.
This has the additional advantage that running on the scripts out of the Ganga build target is executing the same commands as you would when running locally, so less differences between Local/Batch/Grid running.


In the case that a user just wants to run a vanilla release of DaVinci with different options to production this is a special case.
Ganga (GaudiExec) still requires for the Ganga build target to exist for the vanilla build target. This makes life difficult as either there has to be a pre-built target distributed by CVMFS which Ganga can use or Ganga has to wrap up the default application build-area you get from an `lb-dev` command.
Distributing a pre-built target on CVMFS unfortunately has several disadvantages which includes a lot of code to look for a specific build-target, and, if there is a bug in the release would require some horrible hacks to work around it. (you can't (well really, should NEVER) change a file on CVMFS)
It was decided after some discussion it is much easier to request users to build a simple target once for submitting default DaVinci applications as this allows for fixes from the LHCb lb-scripts to be rolled out into production rather than requiring a re-release of all of the LHCb apps effected.
The situation may have changed, and if so it might be sensible to re-visit but I think the original ideas pushing for this model of working are better.

There is a question about whether the LHCb documentation should teach people how to use the tools or how they work and I'm strongly leaning toward the documentation being re-written with more of a focus on the latter.
