### ISSUE TITLE
Application checkout

### ISSUE THREAD

**Issue by moredanphysics** [ganga-devs/ganga#1281]
Hi @rob-c , @egede , Taking one further step back, why does DaVinci need to be checked out at all? Why can't the grid job just execute "lb-run" somewhere? Or is this an LHCbDirac limitation?

PS: Rob I see you mentioned a complication from the lhcb scripts that I can't say I understand... why does this stop us running lb-run?

See https://github.com/ganga-devs/ganga/issues/1279#issuecomment-393815857

**Comment by rob-c** [comment]
Just adding my comments again from #1279 (see below).

There are potential problems introduced in expecting ganga to grab a pre-built target of an application from cvmfs that it was felt could simply be avoided by requiring a user actually build their own target to submit with their jobs.

The only way around this is to give ganga the ability to look for a pre-built target on a worker node (in the CVMFS mount) for an application and then to un-tar it to the WN directory.

This introcudes problems including what to do if the target ever needs re-building for a historical release due to a change in the `lb-*` applications.

With this in mind it was felt the best solution is to require a user always build a target before submitting a job.

The much better apporach (imo) is to do something like:

(pseudo-code):
```
myApp = prepareGaudiExec(...)
myApp.prepare()
box.add(myApp)
j=Job(...)
j.application = box[..]
j.application.extraOpts = ...
j.submit()
```

The above approach has the advantage that you only ever pre-build the application target once if needed.

The target is then stored (pre-built) in your ~cmtconfig space~ shared application area in ganga and you only ever need to re-compile if there is some change elsewhere in the LHCb stack.

Due to ganga's inheritance model changes made to j.application __do not__ impact the  stored myApp or object in the `box` repo.

This doesn't require the release process for LHCb apps to change or for historical releases on CVMFS to have to be touched. (both of these are extremely good things).



> My original comment from #1279
```
Hi again,

OK the job submission broadly has the following constraints:

Ganga doesn't know what (if anything) has been changed in a project.
i.e. Ganga has no way of querying does this LHCb application need to be rebuilt each time.
How should Ganga construct the environment for the job on the worker node?
i.e. How if something has changed should this overload the default components on the worker node.

These 2 problems are solved by the new LHCb build system having a Ganga build target.
This builds all of the required files needed to run a job into 1 .tar.gz target file.

This allows Ganga to capture this build-target for an application, arrange for it to be transferred to the worker node, then it additionally provides a consistent entry point which handles all of the environment initialisation within the LHCb build system.
This has the additional advantage that running on the scripts out of the Ganga build target is executing the same commands as you would when running locally, so less differences between Local/Batch/Grid running.

In the case that a user just wants to run a vanilla release of DaVinci with different options to production this is a special case.
Ganga (GaudiExec) still requires for the Ganga build target to exist for the vanilla build target. This makes life difficult as either there has to be a pre-built target distributed by CVMFS which Ganga can use or Ganga has to wrap up the default application build-area you get from an lb-dev command.
Distributing a pre-built target on CVMFS unfortunately has several disadvantages which includes a lot of code to look for a specific build-target, and, if there is a bug in the release would require some horrible hacks to work around it. (you can't (well really, should NEVER) change a file on CVMFS)
It was decided after some discussion it is much easier to request users to build a simple target once for submitting default DaVinci applications as this allows for fixes from the LHCb lb-scripts to be rolled out into production rather than requiring a re-release of all of the LHCb apps effected.
The situation may have changed, and if so it might be sensible to re-visit but I think the original ideas pushing for this model of working are better.

There is a question about whether the LHCb documentation should teach people how to use the tools or how they work and I'm strongly leaning toward the documentation being re-written with more of a focus on the latter.
```

**Comment by mesmith75** [comment]
Won't fix.
