### ISSUE TITLE
Ganga is eating disk space

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1344]
Ganga is eating disk space even without downloading `outputfiles`. #1145 needs finishing to solve this.

My gangadir is ~18G of which 6G is in the repository, 4G in the sharedir, and 7.5G in the workspace. 6G for the repository seems excessive?

**Comment by mesmith75** [comment]
Looking at the repository, this is due to the input data - implementing #1258 would help us out. The explosion of the number of LFNs per dataset is really not helping, nor is storing them all for every job, even if we only use a fraction after splitting.

**Comment by egede** [comment]
We talked about storing the list of strings as a compressed object both in memory (until need) and on disk. See https://stackoverflow.com/questions/19500530/compress-python-object-in-memory for this. I guess you just want to compress the `repr` of the list of strings rather than do a pickle first.

**Comment by mesmith75** [comment]
The pickle would take out the leg work I think.

**Comment by egede** [comment]
Not quite sure what you mean. I fear the pickle will make the object less 
compressable.

**Comment by rob-c** [comment]
@mesmith75 I'm aware this is probably the biggest performance hit when using Ganga on LHCb in terms of cpu, memory and disk I/O.
Would it be worth biting the bullet here and starting from scratch on a new LHCbDataset object which is actually a factory which doesn't store full fat DiracFile objects in memory at all times and stores a compressed base64 object in the XML?

I'm GEOC at CERN 3rd-7th Dec so I can throw some dev time at this with an LHCb hat on.

**Comment by egede** [comment]
We are saving a factor 2 already with #1377 but I agree that this would be a good thing to do. As there are many potential side effects, I think some careful discussion about design would be required before actually starting to code it.

**Comment by mesmith75** [comment]
Yes that is the ultimate intention. I was hoping #1258 would take us in that direction but it didn't work out quite as I had hoped.

**Comment by rob-c** [comment]
OK, I've mocked up a replacement LHCbDataset which correctly acts as a factory around an internal catalogue of LFN/PFN which it stores in a compressed format on disk.
Early tests show a 200x+ reduction in the disk usage which is very good with much better job load times.

However I've 2 questions around this.

1. Is the intention that Schema upgrades be incompatible with previous versions?

If so I don't see any benefit to having the version check be explicit and I might as well call a new class a new name. This would require adding a method to explicitly convert existing jobs to save storage on disk.
The scenario here is if myClass(v2) can never load myClass(v1) XML objects and having myClass(v2) means jobs with myClass(v1) members on disk can never be loaded again I don't see any benefit over having myClass(v2) over SomeOtherClassName(v1).

I would propose changing the Schema to allow forward loading of old objects but not backwards. i.e. myClass(v2) can read myClass(v1) XML but not myClass(v3) to avoid object corruption. (obviously myClass(v3) has to be able to read myClass(v1) but that's just the code-cost of using a versioning Schema over replacing the objects).

2. Should Ganga move whole-hog to a new file format, something like data.xml.zip ?

This would mean that Ganga stores the XML in an easily compressible format which offers minimal overhead when performing I/O. (and in the case of AFS I'd reckon offer large performance improvements).
This doesn't directly address the CPU/Memory cost of the current LHCbdataset but it does mean that the I/O component of the poor performance is dramatically reduced.
Of course this is a major change from the perspective of the program and would render all touched objects inaccessible to older versions of Ganga.
(unless you consider adding the ability to fall back to .xml.zip files now and then in a future version make this the default)

**Comment by egede** [comment]
A few comments. Is the internal catalogue a monolithic thing on disk shared between all jobs. If yes, will it grow forever as old entries are never deleted?

We do not see the issue of forward migration as a problem. So if you start Ganga in the new version, then any job object declared dirty, will be re-written in the new format. This means that for those jobs, they can no longer be read in the old version. Migration forward has to be well planned for the user, but we believe this is acceptable.

For the question about a bigger change of file format, please open a new issue.

**Comment by rob-c** [comment]
OK, catalogue is maybe a too strong name, this is a list of strings that contain only the data required to rebuild the job object in the minimal form. (Arguably this could even be the full xml rep of the object, but most of the XML is not needed for 99% of the file actions.)

OK, so you would potentially be happy with Ganga supporting forward only migration?
If so that's a 1 line fix when I make a PR with the new dataset object for comments.

I've uploaded a quick draft of what I used to show that it's possible to subvert the writing process using only the class in question to write a smaller XML compared to what we do normally.
[LHCbDataset2.zip](https://github.com/ganga-devs/ganga/files/2590076/LHCbDataset2.zip)

When a LHCbDataset object is changed in XML to be LHCbDataset2 this class (on disk by hand) will load it, extract the LFN/PFN in the file contents into a list stored in the class and only saves a compressed, encoded version of this list when ganga closes.
This results in a 200k LHCbDataset containing 100 DiracFiles to be condensed down to a 1k LHCbDataset2 which contains 99% of the information of the earlier dataset.

This hasn't been used yet to submit jobs or do anything more intensive (It's largely incomplete) but I'll have a look at trying to submit a test job with this in December.

As for changing file format this was more of a gauging the interest if it's worth pursuing or not?
