### ISSUE TITLE
strange entries in newly created .gangarc (ganga 7.1.12)

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1443]
What are they supposed to mean:
```
[defaults_Job]
#application = <GangaCore.Lib.Executable.Executable.Executable object at 0x2b7f0634c628>
#backend = <GangaCore.Lib.Localhost.Localhost.Localhost object at 0x2b7f06353260>

[defaults_JobTemplate]
#application = <GangaCore.Lib.Executable.Executable.Executable object at 0x2b7f06362368>
#backend = <GangaCore.Lib.Localhost.Localhost.Localhost object at 0x2b7f06362208>
```

**Comment by mesmith75** [comment]
As far as I am aware they are not new. They are just the defaults when you create a new job (`j = Job()`),

**Comment by JacekHoleczek** [comment]
I did NOT create any job.
I just started ganga 7.1.12 for the first time and it created a completely new fresh ".gangarc" (from scratch).
Moreover, each time I recreate ".gangarc" from scratch, I get different "object at" addresses.

In the old ganga 6.0.44 ".gangarc", I find:
```
#application = None
#backend = None
```

**Comment by mesmith75** [comment]
There is so much different between 6.0.44 and the latest. We are not going to keep going back over old changes.

As I say these just set what the defaults are when one creates a new job. i.e. you could change the default application to be a ROOT one instead of executable, or the default backend to be DIRAC or whatever you like. The only thing is somewhere along the way we explicitly set the default in the configs.
