### ISSUE TITLE
INFO line for a completed task missing (ganga 7.1.12)

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1453]
The good old ganga 6.0.44 informed me that the task was completed (finished).
This is now missing in the new ganga 7.1.12.
I get plenty of "INFO" lines for all individual jobs but there is no "final" line which says that my whole task completed / finished.
Could you, please, add it back (and please make sure that it automatically "flushes" the screen / terminal output so that, when "everything is ready", I get it automatically on the screen, without any need to press "enter" from time to time in order to see if any new INFO is in the "screen stream buffer").

**Comment by mesmith75** [comment]
We can look into the missing task finishing print out.

As for the second part that is deliberate - we had a _lot_ of complaints when the logger is not cached. ~~Perhaps we can make it configurable if you are desperate.~~

Edit: Turns out it already is configurable. In the `[Logging]` part of your .gangarc set `_interactive_cache` to `False`.

**Comment by JacekHoleczek** [comment]
Sorry, "caching" intermediate output is fine ... just the very final "task completed" should flush it automatically (regardless of the `_interactive_cache` setting).

**Comment by mesmith75** [comment]
That is rather less feasible.
