### ISSUE TITLE
Remove job names from SGE backend

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1482]
The Imperial batch doesn't allow for job submission with job names. It would be nice to fix SGE such that submission works but ganga still lists the jobs with names.

A similar but not fatal problem is:
```python
INFO     could not match the output and extract the Batch queue name
```

**Comment by JacekHoleczek** [comment]
I also always get the "could not match ..." messages with any ganga version (e.g. 6.0.44 and 7.1.x) and any batch system that I used (i.e. PBS, SLURM).

If I understand it well, you can change the SGE "submit_str" in your ".gangarc" so that it suits local "Imperial" rules.

I guess, if you completely change the way ganga manages SGE (by removing the "job name"), another people who use SGE may then get into problems with their local batch systems (where "job names" may be required / convenient).

**Comment by mesmith75** [comment]
Ah, I didn't realise it was just the submit string - thanks!
