### ISSUE TITLE
Call DIRAC.killJob() when removing jobs

### ISSUE THREAD

**Issue by fstagni** [ganga-devs/ganga#1503]
All in the title: it seems that jobs are not removed by DIRAC when they are removed from Ganga backend.

**Comment by egede** [comment]
If a job is removed in Ganga it attempts to kill any running jobs and subjobs, see https://github.com/ganga-devs/ganga/blob/d4fa1cce3cf5d4d8d8a3fdc990cfdf1d82b41ef4/ganga/GangaCore/GPIDev/Lib/Job/Job.py#L1664 . However, if the kill command throws an exception, the job is removed anyway and there might be orphans left.

- Removing jobs even if the kill fails seems correct to me. Otherwise you could end up with jobs in Ganga that cannot be removed.
- The kill command to Dirac might fail if there is a problem with the proxy, a lack of network connection or similar. However, in the absolute majority of cases it should work.
- Another way that orphans can be created is if Ganga for some reason fail to record the Dirac id's of the individual jobs. This can happen if the Ganga process is terminated in an abrupt way (user suspending laptop where their ssh session started or similar).

**Comment by mesmith75** [comment]
So we have been using `DIRAC.deleteJob` which according to the docstring should be sufficient to kill it first.

**Comment by fstagni** [comment]
Lately we have seen cases where users are asked to delete a large number of faulty jobs. They did in Ganga, but DIRAC jobs never received got killed. It happened frequently enough that makes me think that there's something wrong in the logic somewhere. I will let you know when it happens. 

In the meantime, I cc @VladimirRomanovsky

**Comment by mesmith75** [comment]
There may be an error in our logic for killing large numbers of jobs - I'll check.

Looking through the Dirac code it is not entirely obvious to me that `deleteJob` ensures a job is killed. Maybe we should make the change in any case.

**Comment by fstagni** [comment]
I can confirm that `deleteJob` indeed also kills them.

**Comment by mesmith75** [comment]
I have been unable to produce a problem with my tests. All the jobs and subjobs get killed successfully. I'll keep an eye out in the future for issues.

In any case I have added a check to make sure that everything does get killed in #1520
