### ISSUE TITLE
Write Unit tests for the GangaFile classes

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1627]
All the classes in https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaCore/GPIDev/Lib/File that inherit from `IGangaFile` should have unit tests written and placed in a directory `GangaCore/test/Unit/Files`. The `mock` module should be used to prevent that the testing is waiting for any external services.

**Comment by RajatSingh95** [comment]
@egede I would like to work on this. Currently, I am looking over the unit tests for existing classes to get a better understanding.

**Comment by egede** [comment]
> @egede I would like to work on this. Currently, I am looking over the unit tests for existing classes to get a better understanding.

You are welcome.

**Comment by anastr0** [comment]
Can I start writing these tests? :D @egede

**Comment by egede** [comment]
@anaswaratrajan Yes, you are welcome. Note the comment about the use of `mock` from the `unittest` package to ensure that these tests are not dependent on any external services.

**Comment by joj0s** [comment]
I am currently working on this one.

**Comment by joj0s** [comment]
I have a question about mocking methods that are part of Ganga classes, but not part of their exported Schema. 

For example in [MassStorageFile.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py) I would like to patch the [_mkdir function](https://github.com/ganga-devs/ganga/blob/b3dec32b47101a9bac465ed5e83e5e475fafd837/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L212) so as not to make an external call to a subprocess, but doing so raises an AttributeError in `unittest.mock` since `_mkdir` is excluded from the class schema. 

Is there any way that is possible?

**Comment by joj0s** [comment]
@egede @alexanderrichards I solved the above issue using the `_impl` method as you suggested. 

However, when testing the remove method for `MassStorageFile.py` I ran into another problem:
As you can see [here](https://github.com/ganga-devs/ganga/blob/b3dec32b47101a9bac465ed5e83e5e475fafd837/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L487) this method is supposed to read the appropriate `rm` command and execute it, but in the default `.gangarc` config, that command is not defined and I get a `KeyError` when looking for it. Here is what the `uploadOptions` dict includes:
```python
{'mkdir_cmd': 'mkdir', 'cp_cmd': 'cp', 'ls_cmd': 'ls', 'path': '/tmp'}
```

I believe the rm command should normally be included in there. Should I open an issue for that or is there something wrong with my config? Can you on your end successfully remove a mass storage file?

**Comment by mesmith75** [comment]
Looks like an omission here: https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/__init__.py#L820

**Comment by mesmith75** [comment]
Fixed here: https://github.com/ganga-devs/ganga/pull/2031

**Comment by egede** [comment]
Nice to see that unittests are discovering bugs!

**Comment by joj0s** [comment]
Thanks! I'll rebase and finish up the rest of the file tests

**Comment by egede** [comment]
You can rebase now.

**Comment by joj0s** [comment]
I might have found another bug in `MassStorageFile.py`'s remove method. As you can see [here](https://github.com/ganga-devs/ganga/blob/b3dec32b47101a9bac465ed5e83e5e475fafd837/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L513) these 3 lines of code are supposed to go through each Mass Storage file location, delete it, and them remove that location from the inner `locations` list.

The problem is that it uses the `pop` method, which takes in an **integer index** as an argument. However, it looks like `locations` is supposed to contain file paths as strings, as you can see in [this example](https://github.com/ganga-devs/ganga/blob/b3dec32b47101a9bac465ed5e83e5e475fafd837/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L354) where a file path is appended, and the local `i` variable is a `location`. So I believe that the correct method to be used should be the `remove` method. When mocking `locations` to use a dummy list of file paths, it gives me that exact error `TypeError: 'str' object cannot be interpreted as an integer` when the pop method is called

**Comment by joj0s** [comment]
And on a minor sidenote, I also assume that [this is supposed to be a formatted string containing the location](https://github.com/ganga-devs/ganga/blob/b3dec32b47101a9bac465ed5e83e5e475fafd837/ganga/GangaCore/GPIDev/Lib/File/MassStorageFile.py#L514), right?

**Comment by egede** [comment]
Yes, indeed. For any new edits of string processing, please use f-strings instead.

**Comment by joj0s** [comment]
I am also having some trouble mocking Grid credentials when testing [LCGSEFile.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/GPIDev/Lib/File/LCGSEFile.py).

I tried mocking the entire `GangaCore.GPIDev.Credentials.credential_store` but I get the following error when trying to run the file's [put method](https://github.com/ganga-devs/ganga/blob/d7b5f9db3b0e37a39a9e93a1df67599c65f54ab3/ganga/GangaCore/GPIDev/Lib/File/LCGSEFile.py#L162)
```python
GangaKeyError: 'Matching credential [VomsProxy()] not found in store.
```

I also tried creating a credential store with fake creds like in [this example](https://github.com/ganga-devs/ganga/blob/d7b5f9db3b0e37a39a9e93a1df67599c65f54ab3/ganga/GangaCore/test/Unit/Credentials/TestCredentialStore.py#L90) but that didn't work either. Do you have any suggestions?

**Comment by alexanderrichards** [comment]
you probably need to mock the `__getitem__` from the `CredentialStore`

**Comment by egede** [comment]
Hmm, should we just remove LCGSEFile? Can we actually see anybody use it?
