### ISSUE TITLE
Condor error finishing job

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1926]
```python
WARNING  --------------------------------------------------
ERROR    Empty stdout file from job 894.0 after waiting 10mins. Marking job asfailed.
ERROR    JobStatusError: list index out of range
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/8.5.0/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 632, in updateStatus
WARNING      self.time.timenow(newstatus)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/8.5.0/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Lib/Job/JobTime.py", line 127, in timenow
WARNING      be_statetime = stripProxy(j.backend).getStateTime(childstatus)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/8.5.0/lib/python3.6/site-packages/ganga/GangaCore/Lib/Condor/Condor.py", line 767, in getStateTime
WARNING      if checkstr == splitLine[0]:
WARNING  IndexError: list index out of range

```

**Comment by egede** [comment]
Two issues here as far as I can see.

- The error from the empty stdout file. The [code](https://github.com/ganga-devs/ganga/blob/95e88336a0bb209fec08e2a8783049e57cd9d44c/ganga/GangaCore/Lib/Condor/Condor.py#L648) in fact contains a comment about this. Not sure that there is much that we can do. I wonder if it is an `/afs` problem.
- The traceback is then a consequence of the that the `condorLog` file in the outputdir is empty. The [code](https://github.com/ganga-devs/ganga/blob/95e88336a0bb209fec08e2a8783049e57cd9d44c/ganga/GangaCore/Lib/Condor/Condor.py#L730) simply needs protection against the situation where the file does not have the expected structure. In this case, it is caused by an empty file, but there could be other issues I guess.
