### ISSUE TITLE
CREAM jobs stuck with old status

### ISSUE THREAD

**Issue by joezuntz** [ganga-devs/ganga#199]
After some kind of update failure in checking the status of my jobs (I think this was a timeout, though apologies, I don't have the error message I got), their states have not continued updating.  When I check them directly with glite-ce-job-status it shows them as having finished (though failed).  

Apologies if this is not strictly a ganga problem but rather with another part of the system, or if I have misunderstood some other aspect of this - I'm very new to grid computing in general.  

But if this is a ganga issue might there be some way to restart the monitoring of a job perhaps? Or something else I should do?

See below for an illustration

```
[11:46:01]
Ganga In [30]: j=jobs((266,2))  #I have a number of jobs like this, some stuck as "running" some as "submitted"

[11:46:06]
Ganga In [31]: j.status
Ganga Out [31]: 'running'

[11:46:10]
Ganga In [32]: j.time
Ganga Out [32]: 

         Time (UTC)   Status
- - - - - - - - - - - - - - - - - - - - - 
2016/02/10 14:17:58 - new
2016/02/10 14:18:01 - submitting
2016/02/10 14:18:17 - submitted
2016/02/10 14:18:34 - running


[11:46:16]
Ganga In [33]: !date  #To show how long they have been like this
Mon Feb 15 11:46:20 GMT 2016

[11:46:20]
Ganga In [34]: j.backend.id  #Will use this below to check manually
Ganga Out [34]: 'https://lcgce03.phy.bris.ac.uk:8443/CREAM734329072'

[11:46:46]
Ganga In [35]: quit()

Ganga.Core.InternalServices        : INFO     Stopping Job processing before shutting down Repositories
Ganga.Core.InternalServices        : INFO     Shutting Down Ganga Repositories
Ganga.Runtime                      : INFO     Registry Shutdown



# Now looking at the status manually
-bash-4.1$ glite-ce-job-status https://lcgce03.phy.bris.ac.uk:8443/CREAM734329072

******  JobID=[https://lcgce03.phy.bris.ac.uk:8443/CREAM734329072]
    Status        = [DONE-FAILED]
    ExitCode      = [N/A]
    FailureReason = [Job has been terminated (got SIGTERM); reason=-10]

```

**Comment by joezuntz** [comment]
I've now seen another example of the warning message which (I think) preceded this problem:

    Ganga.Utility                      : WARNING  exit status [1] of command ${GLITE_LOCATION}/bin/glite-ce-job-status -L 2 -n -i /tmp/tmpH1cisA.jids
    Ganga.Utility                      : WARNING  <first 4096 bytes of output>
    2016-02-15 15:51:20,158 FATAL - JobInfo

    Ganga.Utility                      : WARNING  <end of first 4096 bytes of output>

**Comment by afortiorama** [comment]
I asked the sys admins in Bristol to see what is going on. It may help with understanding why ganga doesn't get that DONE-FAILED, but I wouldn't hold my breath.

**Comment by rob-c** [comment]
@joezuntz What version of Ganga are you using?
There have been issues which have become more exposed recently to do with repository synchronisation and the monitoring loop within Ganga becoming stuck.
If the monitoring is failing to progress my best advise is to minimise the number of jobs stored in your jobs repository or wait for 6.1.16 which is specifically addressing these issues

The failing to read the firs 4k of data from the status file is typically because the file no longer exists on the backend. I think this could be a glite bug in not progressing finished jobs to a finished state.

I don't know how Ganga reacts to the job being missing on the backend but I assume that (maybe) if the job has been cleaned up externally to Ganga then Ganga will struggle to progress the job to a 'completed' or 'final' state.
If this is the case I suspect this could be a problem with the Glite backend within Ganga but I've never used this system so can't comment particularly about it.

**Comment by joezuntz** [comment]
Hi @rob-c  - the problem first appeared with 6.0.42-hotfix1 but I've since updated to the bleeding edge version and it still seems to be there.

I can't really limit the number of jobs I run because of the nature of the problem we are working on.  Do you have a sense of when 6.1.16 might be available?

Paging @afortiorama for her information as she is looking into this on the other side.

**Comment by rob-c** [comment]
@joezuntz Hopefully within the week 6.1.16 will be out, we're waiting on a final small subset of patches before we head for release.
OK, if you've been seeing this as a problem with the jobs on Glite then this is likely an issue with the backend at some level either within Ganga or a possible change in the glite tools.

**Comment by joezuntz** [comment]
In case it's useful we've discovered that in this case the jobs were killed by the batch system of the site in question. Thanks for the info on 6.1.16.

**Comment by rob-c** [comment]
@joezuntz 6.1.16 is now available on cvmfs and ```pip install``` if you're able to try this version.
