### ISSUE TITLE
User defined output LFN for DiracFile

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#201]
A user should be able to define the LFN for a DiracFile. The support within the Dirac API seems to be in place.

https://its.cern.ch/jira/browse/LHCBDIRAC-299
https://its.cern.ch/jira/browse/GANGA-1921

**Comment by rob-c** [comment]
The change of LFN for the output of the job needs a new field in the DiracFile and support in the (LHCb?)Dirac backend to pass the correct option for where files are to be uploaded to.

This should be a quick afternoon job but keeps getting distracted for other tasks.

I'm planning to make 6.1.17 available to LHCb users as a development release ahead of 6.1.17 final (there are a lot of LHCb related fixes not going into 6.1.16) I'll try and do the work for this in a PR for 6.1.17 as it shouldn't take too long to do.

**Comment by rob-c** [comment]
I've just had a look at the LHCbDirac api and it still looks like the jobs are constructed with the jobID in the name:
```
This method is used to supplant the standard job wrapper output data policy for LHCb.

      The initial convention adopted for user output files is the following:
      /lhcb/user/<initial e.g. f>/<owner e.g. fstagni>/<outputPath>/year_month/<jobID/1000>/<jobID>/fileName

      But, if prependString is set, then the following is adopted:
      /lhcb/user/<initial e.g. f>/<owner e.g. fstagni>/<outputPath>/<jobID>_<prependString>_fileName
```

The latter carries the limitation that the ```fileName``` component can't have a ```_``` character within it.
(This is due to something at the Dirac level beyond our scope)

I plan to catch and throw a Ganga error on this as it would be nicer than waiting for the job to fail due to LHCbDirac not returning a similar error.


I've included pseduo-code which shows how the generic Dirac deals with user LFN construction.
The name mangling is very similar only the behaviour to LHCb.

```
user_prefx = VO specific Operations option used for building user LFNs
...
basePath = '/' + vo + '/' + user_prefix + '/' + <initial e.g. f> + '/' + <owner e.g. fstagni>
...
if not outputPath:
  outputPath = <jobID/1000>/<jobID>
else:
  outputPath = OutputPath
lfn = os.path.join( basePath, outputPath, os.path.basename( fileName ) )
```

Both vanilla Dirac and LHCbDirac construct similar enough LFN that the base of the LFN can be taken to be:
```
/vo/user_prefix/<initial e.g. f>/<owner e.g. fstagni>/
```

Then the fileName is effectively decided on top of this.

The LHCb naming convention for user files appears to be:

```<outputPath>/<jobID>_<prependString>_fileName``` or ```<outputPath>/year_month/<jobID/1000>/<jobID>/fileName```

However the Dirac naming convention is only to use:
``<outputPath>/fileName`` or ``<jobID/1000>/<jobID>/fileName``

I think if we add the ```prependString``` within DiracFile it would be valid as we can change the LFN structure for the Dirac backend to be:

```<prependString>_fileName``` from within Ganga.


There is just the decision on whether we want to limit vanilla Dirac users from not using the ```_``` character in their filenames?
We can't dynamically change the fileName to not include a ```_``` character within Ganga as this is the output from the user. However, I think it's perfectly fine to add it as a 'generic' requirement that if the user wants to use the new attribute corresponding to the ```<prependString>``` then they should be aware of this limitation.

**Comment by rob-c** [comment]
I think I'll look into this for 6.1.20 as it would be nice to have for both LHCb, LSST and others
