### ISSUE TITLE
Gangadir reappears after deletion

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2084]
From mattermost:

"
ages ago I tried changing gangadir to EOS, then changed it to AFS work (Apparently ganga and EOS don't mix). Now I have a permanent ghost dir in EOS which reappears even after deletion! (Ganga rc doesn't have that line anymore)
"

**Comment by egede** [comment]
If the whole gangadir was copied from one location to the other
```
cp -pr /eos/..../gangadir /afs/work/..../mydir
```
then the repository will still have multiple links to the old location written into the `inputdir` and `outputdir` locations. That could maybe cause it to be recreated. Another option is that there is still some ghost process running Ganga on an lxplus machine. If the `gangadir` was changed, it will not be blocked from writing due to the lock file getting removed.

Can you add the user here or get back to them for some more details.

**Comment by GSarpis** [comment]
Adding detail:
I changed my ganga dir to EOS:
```
/eos/lhcb/user/g/gesarpis/gangadir_eos  ## Gedas 12.07.22 change
```
This created a directory 
```
/eos/lhcb/user/g/gesarpis/gangadir_eos/gangadir_eos ## Gedas 12.07.22 change
```

(I wasn't aware of the comment problem) 

Then I changed it to:
```
gangadir = /afs/cern.ch/work/g/gesarpis/gangadir_work
```

which works as expected, but the EOS dir would be created even after deletion. 

Recently I tried "eos rm _fullpath_" and the EOS directory hasn't appeared in a couple of days.
