### ISSUE TITLE
ganga INFO messages

### ISSUE THREAD

**Issue by afortiorama** [ganga-devs/ganga#233]
Hi,

I was wondering if there is a way to quiet down the messages about the change of status. They tend to be a bit tedious when one runs more than a handful of jobs. They are also multiple lines per job

Ganga.GPIDev.Lib.Job               : INFO     job 245.3 status changed to "completing"
Ganga.GPIDev.Lib.Job               : INFO     Job 245.3 Running PostProcessor hook
Ganga.GPIDev.Lib.Job               : INFO     job 245.3 status changed to "completed"

A summary table would be more useful for example (I know it is easy for the user to write but still)

Tot 1, Perc 0.0% completing
Tot 653, Perc 24.5% running
Tot 2008, Perc 75.4% completed

**Comment by afortiorama** [comment]
I guess 

disableMonitoring()

will do it.

**Comment by rob-c** [comment]
@afortiorama There is no way to reduce the verbosity other than to change the logging level. Although I can't remember if there is a level higher than info.
Trying to intercept and summarize these tasks requires a major re-write of the logging infrastructure which isn't on our todo list atm.
The ```disableMonitoring()``` disables the monitoring of the jobs and is probably not what you want.

**Comment by rob-c** [comment]
Do any of the other ganga developers have any input on this?

**Comment by alexanderrichards** [comment]
I agree with @rob-c `disableMonitoring()` will reduce the output you see but at the expense of not actually monitoring your jobs which is probably not what you need.

levels warning and error are above/below (whichever way you look at it) info so you could only accept Job logs with one of these levels if you like. This would at least work as a solution but you would then have to check the jobs table to see when your jobs have finished. This is probably your best bet at the moment if you want less output but you probably only want this setting for the Job logger otherwise you might miss other information.

---
 I would add though that in my opinion the message:
```Ganga.GPIDev.Lib.Job : INFO Job 245.3 Running PostProcessor hook```

could probably be a debug

**Comment by rob-c** [comment]
@alexanderrichards I would fight against this becoming a debug statement (for now) as we have had errors where people are exiting jobs taking a long time to complete due to running post-processors which deal with things such as moving GangaFile objects around at the end of jobs (potentially >100Mb of file transfers over unknown connection speeds)

**Comment by afortiorama** [comment]
@alexanderrichards disableMonitoring is definitely not what I want. I tried and it stops updating everything. Are you suggesting I should set Ganga.Utility.logging ERROR in .gangarc?

**Comment by afortiorama** [comment]
I set Ganga.GPIDev = ERROR this seems to remove the jobs info.

**Comment by alexanderrichards** [comment]
I was suggesting that you set the specific Job Logger to Error or Warning level by adding the following to your `~/.gangarc`

```ini
[Logging]
Ganga.GPIDev.Lib.Job = WARNING
```

**Comment by alexanderrichards** [comment]
Since it's the info level messages that you want to reduce I would recommend setting the level to `WARNING` rather than `ERROR` as you will otherwise miss any actual warnings that you might need to be aware of

**Comment by afortiorama** [comment]
I tried also your recipe and it works too. It still leaves some info but not as much.

**Comment by alexanderrichards** [comment]
> It still leaves some info but not as much

This is because it has only raised the level of the Job object rather than all of the GPI objects

**Comment by milliams** [comment]
I'm closing this as there is no specific action to take.
