### ISSUE TITLE
GangaFile put and remove statements should return True/False

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#26]
It has been requested that GangaFile objects return True/False for put and remove commands so that scripts and monitoring tools can determine if an action has completed successfully.

We already do this for setLocation and I think this should only be a few lines of code to change but I'[d prefer to leave it until 6.1.13 to implement this.

**Comment by milliams** [comment]
I've just had a look at this and we don't already do this for `setLocation`. The current situation is:

IGangaFile | MassStorage | Dirac | Google | Local | LCGSE
---------------|------------------|--------|-----------|--------|-----------
`setLocation` | `None` | `None` | N/A | N/A | `None`
`location` | `list` | `list` | N/A | `list` | `list`
`get` | `None` | `None`,`dict`,`list` | `None` | N/A | `None`
`put` | `None` | `None`,`str`,`list` | `None`,`list` | N/A | `None`
`remove` | `None` | `None`,`dict`,`list` | `None` | `None` | N/A

So `location` is quite well behaved (as we would expect since the return value is actually used by people). `DiracFile` is a bit strange at times since it will sometimes return the value from `DiracUtilities.execute()`. Apart from `DiracFile` I think there should be no problem changing these to return a `bool`.

**Comment by milliams** [comment]
I think you fixed this in your recent PR @rob-c? Could you tag it with the appropriate version and mark it as closed?

**Comment by rob-c** [comment]
No, we're nowhere near properly supporting this. There is still work to be done to support this way of working which I may get around to over the next few weeks.
