### ISSUE TITLE
Revert isType Migration

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#30]
@drmarkwslater requests at least a partial revert of the isType migration introduced in commit https://github.com/ganga-devs/ganga/commit/8df5de9f4db39bf48f317c372485738e3cc1c262.

For additional details, see the discussion in the commit, starting:
https://github.com/ganga-devs/ganga/commit/8df5de9f4db39bf48f317c372485738e3cc1c262#commitcomment-14154666

I suggest all discussion now migrates to this issue to keep it centralised.

**Comment by rob-c** [comment]
@drmarkwslater Additionally accessing the ._name attribute of an object is often only possible when the object has been stripped of it's proxy. Other than checking for the type of an object by using this attribute (or .__class__.__name__) I don't see what is gained by using this attribute in the code?

Making use of isType allows the programmer to use isintance (which is useful for LHCbDataset vs GangaDataset) as well as not caring about whether the object in question is behind a proxy or not.

In the case of .__class__.__name__ comparisons we shouldn't really be using this for type comparisons (or imo at all) which is why I've replaced them with the (more compact) isType throughout the Core.(

I also added the getName function to get the correct name of a class based upon whether it's behind a proxy.)

**Comment by drmarkwslater** [comment]
[answering comment from commit https://github.com/ganga-devs/ganga/commit/8df5de9f4db39bf48f317c372485738e3cc1c262]

@rob-c I understand why it was done, it's just that in this case it's produced some unintended consequences which, to be honest, I don't want to spend a long time trying to understand and fix "properly" when the code will hopefully be completely retired in the near future. What you suggest could certainly work and would probably fix the issue at hand but may uncover others that we're not aware of at present. I'd much rather just revert the change for the moment to get a working version out (6.1.12 release has this bug as well) and come back to it later if necessary.

**Comment by drmarkwslater** [comment]
@rob-c Again, I don't have a problem with using isType over the _name comparison - perfectly sensible :) - it's just that we currently have a broken release out (for Atlas at least) and I think getting that fixed without introducing any other issues should be priority.

**Comment by rob-c** [comment]
@drmarkwslater  when I fixed this properly the credentials were intialized out of order due to a problem with when they are required at ganga startup. For these files the easiest thing to do is revert the patch.

Part of the isType/getName commits were introduced as I was having to cope with a few oddities from the LHCb code that proxied objects were needing to be used and were causing errors (my LHCbDataset vs GangaDataset in various places being the main one).
I ended up doing this all in bulk to avoid too much commit noise for each file but reverting the patches will introduce bugs from the LHCb side I fear.

**Comment by drmarkwslater** [comment]
@rob-c I don't have any problem with any of the other aspects of the commit (or at least, I haven't found any bugs relating to them!) but for the GridProxy.py (and AfsToken.py I assume) files, the revert will certainly fix the Atlas issue we're seeing. Maybe just do another commit to revert these files?

**Comment by rob-c** [comment]
Will do, I'm going to put in some commits and make a (hopefully) final pre in a few minutes and do some more LHCb testing.

**Comment by drmarkwslater** [comment]
Cool - Thanks Rob!

**Comment by rob-c** [comment]
I'll revisit this particular example at some point during 6.1.14 as this looks like something inconsistent going on in the Schema initialization and it would be nice to know what it is.
I know the code is being deprecated but if this is some strange undocumented behaviour it's best it is understood.

I suspect that this could either be a race condition depending how the first category is populated or a case that default objects are doing something funny as I see some really horrible errors when I change the GridProxy to check for ```not isType(self.commands, ICommandSet)``` which should be functionally identical to what is going on.

Interestingly both the AFS and Grid credentials initialize correctly if the if statements are completely removed which makes me wonder why they might be there at all...

**Comment by drmarkwslater** [comment]
This is what worreid me :) Basically, from the schema it should be 
initialised to ICommandSet and I assumed this function would set it to a 
Voms/Grid command set depending on whether a voms config value is set. 
However, this must be getting set somewhere else because, as you say, by 
the time this code get's called it seems to already have a VomsCommand 
set (or at least when I was looking at it...). I agree a more in depth 
look would be a good idea just to understand exactly what order things 
are happening in.

**Comment by rob-c** [comment]
OK finally I can shed some light on this while the report for 6.1.13-pre is compiling...

For some reason this code is called right at the start of Ganga in loading the LCG plugin. This strikes me as it would be prone to failure if there was some problem with the proxy/grid setup. I suppose we'll get a better fix for this when the credentials branch is mainlined.

Firstly the command ```GridProxy,chooseCommandSet()``` is called numerous times throughout the running of the class despite this looking like an initialization decision for the proxy. (Again this will be deprecated so I can skip the fact that I find this a bit confusing)

When ```isType(..., ICommandSet)``` is first called the test of is this a voms or grid Proxy is performed.
The first time around the value of ```self.voms``` is ```''``` which returns False as it's empty but then this becomes 'dteam' on the gangaat@lxplus account which forces the ```if self.voms``` function to change it's behaviour once the ```self.commands``` have been changed to ```gridCommand```.

As ```if self.voms``` is always True this was repeated many times when using the above type check and the statement ```if self.voms:``` returned True because something had been initialized there. This causes the gridProxy to change to become a VomsProxy.

When ```not isType(..., ICommandSet)``` the test for a voms or grid Proxy is never performed as this variable has been initialized to a 'raw' ```ICommandSet``` object. This causes horrible errors to be thrown.

The correct solution I come to is: ```if not isType(self.command, (GridCommand, VomsCommand)):``` this leads to the self.command only being initialized once to the correct command set.


As for AFSToken I think this is working as appropriate as this is entirely within the __init__ function and is therefore only always called once per instance and I would argue that this particular check here is defunct.

Conclusion. I personally dislike tests to the equivalent of ```if someObject:``` especially when we're working in an environment which allows for Schema defaults to be changed. It's not very implicit and it just causes confusion when the object changes in an unexpected way imo. I know it's very PEP8 in a lot of situations but this doesn't become very readable when debugging imo.
I would argue it's _much_ better to have had ```if self.voms == '':``` which would have removed the problems we see here as well.

**Comment by rob-c** [comment]
I'm not going to revert the reverted patch here I'm simply going to walk away from the old Credentials code as it's all going to be replaced anyway so I'm not going to lose any sleep over this.

I think if this has been understood we can close the issue?

**Comment by alexanderrichards** [comment]
Yes if everybody is happy then please close it.
