### ISSUE TITLE
Migrate Ganga to GangaCore

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#302]
The migration of `Ganga` to `GangaCore` will give a more logic naming convention in Ganga as well as avoiding the overload of the name ganga with just a difference in case. See #297 for further discussion.

**Comment by rob-c** [comment]
Managed to get this down to 3 commands (I think):
```
git mv Ganga GangaCore
find . -name '*.py' -exec sed -i 's/Ganga\./GangaCore\./g' {} \;
find . -name '*.py' -exec sed -i ':a;N;$!ba;s/import Ganga\n/import GangaCore\n/g' {} \;
```
After running this I can submit jobs and the monitoring works without issue.

I think this should cover all of the problems as it moves `Ganga` to `GangaCore` at a module level and then replaces all references to `Ganga.something` to `GangaCore.something` and then catches the remaining `import Ganga\n` by changing them to `import GangaCore\n`.

As this is more of a recipe than a PR and the PR will very quickly get out of date and likely develop conflicts I think it's worth just performing this migration once we're in a state where little is changing (I suppose after the credentials branch is merged perhaps, or before?)

**Comment by drmarkwslater** [comment]
I would say this is something to do just before (or just after) release so as to minimise hassle for any any branches. I personally don't mind when this happens though as you say, probably best to hold off until any major stuff is in.

**Comment by rob-c** [comment]
Think I'm keen to test this before labelling a release 6.2.0, or wait until 6..2.1/6.2.2. it touches almost everything and I'm not sure I want to rush out 6.2.1 because I missed some file when submitting a certain type of job or something or the way we import the scripts. I'd like to see 6.2.0 have no new bugs from us if possible

**Comment by rob-c** [comment]
FYI doing this for 6.4.0 after 6.3.0 would give us initial OSX support for free.

**Comment by egede** [comment]
@rob-c What is the current problem with OSX? I fail to see the connection.

**Comment by rob-c** [comment]
@egede HFS the underlying filesystem in OSX is _not_ case sensitive so trying to do a git clone will get muddled as it will struggle to differentiate between `ganga` and `Ganga`.
This is the same with the default use of NTFS (windows) although this is due to compatibility and NTFS with windows has supported case sensitivity for a while now (I think mileage varies).

**Comment by egede** [comment]
@rob-c OK, given that OS X is essentially unix, I kind of assumed that the file system was fully POSIX compliant. Learn something every day. In any case the change to `GangaCore` is well motivated for other reasons.
