### ISSUE TITLE
auto-resubmit broken

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#327]
An LHCb user is seeing problem with I suspect auto-resubmit as they get errors to the effect of:

```
Ganga.Core.MonitoringComponent     : ERROR    Monitoring Error: local
variable 'try_resubmit' referenced before assignment
```

a few times per minute.

**Comment by milliams** [comment]
This will happen `if len(j.subjobs) > 0` and `if s.info.submit_counter > config['MaxNumResubmits'] or s.status == "killed"` since the variable `try_resubmit` will never be set to anything. That whole function `resubmit_if_required` looks buggy. I'm not sure if it's broken indentation of the `if try_resubmit` and/or some other logic.

**Comment by rob-c** [comment]
@milliams It sounds like you're best handling this issue then, I've not had a chance to look at the code yet.

**Comment by milliams** [comment]
Sure, I'll take a look.
