### ISSUE TITLE
Slow bookkeeping requests

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#370]
It seems like call to the LHCb bookkeeping are very slow for some reason. See the tests below from Zoltan Mathe where he first runs the raw command, and then runs the same within Ganga.

```
In [9]: time res = cl1.getVisibleFilesWithMetadata({'ConfigName': 'LHCb', 'EventType': 90000000, 'FileType': 'BHADRONCOMPLETEEVENT.DST', 'ProcessingPass': '/Real Data/Reco15a/Stripping23r1', 'DataQualityFlag': 'OK', 'ConfigVersion': 'Collision15', 'DataTakingConditions': 'Beam6500GeV-VeloClosed-MagUp', 'Visible':'Yes', 'GotReplica':'Yes'})
CPU times: user 785 ms, sys: 27 ms, total: 812 ms
Wall time: 3.02 s
```

Using ganga the query takes 4 min 43 sec:

```
Ganga In [1]: time BKQuery(path="/LHCb/Collision15/Beam6500GeV-VeloClosed-MagUp/Real Data/Reco15a/Stripping23r1/90000000/BHADRONCOMPLETEEVENT.DST",dqflag="OK").getDataset()
CPU times: user 2min 11s, sys: 1min 14s, total: 3min 25s
Wall time: 4min 43s
```

**Comment by rob-c** [comment]
I'd be keen to check what API is being used for both and how this compares to 6.1.19 as there have been some optimizations around the construction of many, many GangaObjects (in this case DiracFile).
I don't know if we have fixed this but this has been an issue for a long time since we've wanted to take a large BKQuery result and convert it into a list of DiracFiles.

**Comment by rob-c** [comment]
I'm running a quick profile on this but I'm seeing the memory usage on the above command top out at ~700Mb which seems concerning as this is never even written to disk...

**Comment by egede** [comment]
@rob-c Does the memory used if you just estimate the number of characters in the output make sense?

**Comment by rob-c** [comment]
Erm, I'll look at memory usage for the raw call but I suspect there are some bad references to the list which aren't destroyed so we have something like ~200M per-list * 3 + extra stuff

**Comment by rob-c** [comment]
OK, I've got this down to ~2min under a profiler (from about 5) which I think helps, plus memory usage seems to be down rather dramatically. Hopefully this may get slightly better when I run interactively and look at the problem from the Ganga side more.
I'll clean up what I have but it's loosely based off ```features/optimisation``` branch #357 which has some minor bugs I need to fix but hopefully once all of this is in some bottlenecks will be reduced.

I'm just hoping this doesn't vary too strongly due to intermittent machine load

**Comment by rob-c** [comment]
OK, down to 1min and uses about ~280Mb which seems more reasonable. As I say there is some code cleanup but I think I'll incorporate the fixes into #357 as a lot of the bottleneck is passing lists through the set methods in GangaObject and some slow downs with GangaLists.
Obviously I'll have to fix #357 before I look to merge the fixes.

**Comment by rob-c** [comment]
I'll look at #357 as I'm sure I can trim down the number of changes to track down the exact performance bottlenecks in the code. Some of that PR will probably go away but there is some good stuff to keep so I'll clean that up in 6.1.20

**Comment by rob-c** [comment]
This also effects ```box.add``` for large lists of GangaLists/datasets... This __really__ should be looked into imo before 6.2.0, I have an idea where/what to fix (and have fixed it in a really out of date PR by now) but time is needed to fix it properly again on develop.

**Comment by rob-c** [comment]
OK this has received a _lot_ of attention over several months so I think we can say this if fixed. There are problems with handling potentially thousands of DiracFile classes but these are different to this working.
Some queries timeout due to DIRAC problems but repeating the same call in the future 'just works'.
