### ISSUE TITLE
add WN dir to PATH

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#449]
Hi all,

I'm constantly hitting this as a common thing (hence PR such as the one against the Localhost which was ultimately dropped)

Do we have a policy about whether the WN dir where a command is running from should be in the PATH or not?

We already change the env such that we pick up supporting code we ship with jobs to some backends.

Would it be sensible to say that it's a logical extension to include the dir of the WN to the PATH of a job?
(and possibly the LD_LIBRARY_PATH?)

This is would require a relatively minor PR but would remove the amount of times I've been tripped up by having to do this by hand in a job I'm executing.

Does anyone have any thoughts on this?

Rob

**Comment by drmarkwslater** [comment]
I would personally say no we shouldn't add the WN dir to the PATH because by default, this isn't what Linux does, i.e. the PATH variable doesn't contain the current working dir (`.`). I don't think it's hard for a user to specify this in their settings (the `env` option for `Executable` at least) so if that's what they want and are used to then fine, but a user who doesn't expect this to happen may get confused.

Just my 2 cents anyway 😄

**Comment by rob-c** [comment]
it's not _difficult_ for users to do this but I'm certain I've seen this crop up as a support issue quite a few times. 
(_I personally work with ```PATH=.:$PATH``` which does the same in linux and I know quite a few users who expect similar_)
The ```LD_LIBRARY_PATH``` may be a good idea regardless of the PATH as users may ship libraries which need to be picked up by an executable?

It just seems strange to me to not include it in the PATH as this is where the users executable obviously now is and where you would expect to be able to call it from.

I have a situation where I want to upload a large binary now but currently can't add _myexec.bin_ as a string into the ```Executable``` as the PATH isn't set on my WN as I would like. I also can't add ```./myexec.bin``` as a string as the ```./``` is currently forbidden by ourselves.
As a result I end up writing a wrapper script which does just what we're talking about here which feels inefficient.

**Comment by milliams** [comment]
So is the problem is that doing:
```python
j = Job()
j.application.exe = File('test.sh')
j.inputfiles = [LocalFile('nested.sh')]
j.submit()
```
with `test.sh` as
```bash
#! /usr/bin/env bash
nested.sh
```
and `nested.sh` as
```bash
#! /usr/bin/env bash
echo test
```
you see:
```
./test.sh: line 2: nested.sh: command not found
```
?

If so then I agree with @drmarkwslater that the user should not expect to have other scripts in the working directory available in the default search path. They should either set `Executable.env` or change `test.sh` to
```bash
#! /usr/bin/env bash
./nested.sh
```
as would normally be done in a Unix environment.

**Comment by rob-c** [comment]
No the problem is setting ```app.exe = './myexec.bin'``` when I have a large statically compiled app that I just want to run with some args from argsplitter is a royal pain as the user then has to code up some wrapper script which does nothing other than talk to an executable on our behalf.
Having the PATH environment contain the PWD on the WN gets around in a very simple way and avoids headaches for users and for people writing/testing apps.
Yes it's only a short script but I've ended up writing a generic script which will run the 1st arg as the given executable so I don't have a library of 2 line wrapper scripts. This is really an exercise in usability vs design imo.

**Comment by milliams** [comment]
Does doing `app.exe = File('myexec.bin')` work for you?

**Comment by rob-c** [comment]
No because this is a _large_ file which will not be passable in the sandbox. I know this all gets magically fixed with support for IGangaFile but that's not an easy fix and we end up having to examine the PWD to call a file which has arrived in the WN through any other method. This is the same logic as adding ```.``` to the PWD imo

**Comment by milliams** [comment]
I think this basically boils down to "this isn't what `Executable` is for". When you're at the point where binaries are being downloaded from other sources and path manipulation is needed, it's time to write a custom application. `Executable` is useful because it's small and simple and does little.

**Comment by rob-c** [comment]
It makes very little sense to have an Executable vs a DiracExecutable. The actual script (RTHandler) can take care of this but then we end up with 1 backend appearing to examine the WN PWD and then the other doesn't and in principle we could get any file type for running Locally/Batch as well so I'd argue this isn't strictly unique to the Dirac backend at all and is encompassed by the Executable wanting to execute an executable file on the WN in the PWD

**Comment by milliams** [comment]
For reference, at its core, this comes down to [StandardJobConfig](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Adapters/StandardJobConfig.py#L128) which contains:
```python
if isinstance(self.exe, str):
    self.__exe_string = self.exe
else:
    # Get relative path of exe in the sandbox and append it
    # to the inputfiles using self.exe.getPathInSandbox()
```
The second branch is assuming that `self.exe` is a `File`

Discussing it with @drmarkwslater we thought that perhaps, instead of changing `Executable` too much, it might make sense to add a new application called `Command` which simply runs the supplied command in bash on the WN. So
```python
j = Job()
j.application = Command(run='./myexec.bin')
j.inputfiles = [LocalFile('myexec.bin')]
j.submit()
```
would work. The contents of `Command.run` are executed verbatim. This would generate a shell script to run on the WN of:
```bash
#! /usr/bin/env bash
./myexec.bin
```
`Command` is simpler even than `Executable` as it will never copy over any files.

**Comment by rob-c** [comment]
This involves no changes to executable other than to allow users to submit ```./someapp.exe``` rather than just ```someapp``` I'm not convinced a new application object is a sensible thing here unless we're hoping to wean users off ```Executable```?
(I wouldn't say no to as it has the horrible string/File interchangeability in ```.exe``` which imo causes more problems than it solves.)

**Comment by rob-c** [comment]
(I'm planning to open another issue to discuss the JobConfig object which imo should really go the way of the dinosaur but some plugins look like they make heavy use of this still)

**Comment by drmarkwslater** [comment]
One of the benefits of a `Command` application would actually be to make the difference between running and Exe and a command obvious and well defined. Basically:

1. `Executable` for an actual executable file you want to run. This would only accept an `IGangaFile` for the exe argument as it is specifically for running a file itself. A string would default to assuming a `LocalFile`

2. `Command` for running any generic command on the command line. Downside is you have to make sure the file is transferred correctly yourself, the upside is you can run anything you want.

I believe that the semantics we have for `Executable` at the moment were at least meant to be basically 1) above and so I think it makes things more obvious if we properly separate the two use cases rather than try to have the `Executable` app do too much.

@egede @alexanderrichards - Do you have any comments on this?

**Comment by rob-c** [comment]
At this point I fail to see any motivation for keeping around the Executable as it just confuses things an is one of the main users of the ```File``` object that I'm aware of. (I'm not calling to delete it now just to avoid people using it and drop it later by Ganga 6.3 or some other future release when people have stopped using it)

I'm all in favor of a ```Command``` object regardless it would just be a nice simple object which generates simple scripts in the RTHandlers. It would also make testing the IGangaFile scripting tools much easier if there is very little from this application making it to the backends.

**Comment by milliams** [comment]
The `Executable` would be useful to keep around as a 'shortcut' (also essential for backwards compatibility of course). Compare two functionally equivalent hypothetical examples:
```python
j = Job()
j.application = Command(run='./analysis.sh')
j.inputfiles = [LocalFile('analysis.sh')]
```
and
```python
j = Job()
j.application = Executable(exe=LocalFile('analysis.sh'))
```
The latter is simpler and more obvious to new users. Whether that's a *really* good reason is debatable of course.

**Comment by alexanderrichards** [comment]
Hi all, I'm still catching up on this thread so apologies if I say something stupid thats already been covered. I can see that it could be quite nice to have a `Command` application representing bash commands on the worker node as distinct from an `Executable` which would assume a file. i.e. something `chmod +x` . This would need some changes to the existing` Executable` not least because I believe that the default `exe` is the `echo` command which with this distinction feels more (to me) like a `Command`. It's not clear then to me what a sensible default would be such that it's obviously a different entity from the `Command` application but this is a minor point. One could imaging perhaps a simple hello world script that we could ship. 

I can however see that this new `Command` application might be more intuitive for someone (like us devs) just wanting to test a job with a `pwd` or `ls -l` or whatever. I would say though that if we were to do this that we should have a ganga magic filter such that we can simply pass a string positional arg to `Command` rather than having to specify keyword arg `run=` i.e. I think that the latter of the following two examples would be much nicer.

```python
j = Job()
j.application = Command(run='pwd')

j = Job()
j.application = Command('pwd')
```

Anyway just my initial impressions on catching up with this thread.

**Comment by milliams** [comment]
@alexanderrichards I agree with everything you say. I was typing out my response above on the fly and hadn't got to the point yet of sorting out the API. When I'd written as much as `j.application = Command(` I suddenly thought "what should this argument be called?". I went with `run` only because it's short. I agree that it would be good if we could sort out positional arguments for `GangaObject`s as there are other places that would benefit (file types specifically). Doing this centrally would simplify things (we should raise another issue for this though).

**Comment by alexanderrichards** [comment]
> Doing this centrally would simplify things (we should raise another issue for this though)

Agree :+1:

**Comment by egede** [comment]
A long discussion, but I think there is something positive coming out of it. It is clearly the mix-up of the execution of a bash command on the command line and shipping along a script for execution that is causing trouble.

Removing this behaviour by creating a new `Command` application is a good idea and can go ahead as soon as possible.

A few choices are then left to what the next step should be

1. Mark `Executable` for deprecation and not replace it as `Command` allows for issuing a script as 
    well (by separating the `command` and the `inputFile`.
2. Change the behaviour of `Executable` to never accept a command. Giving `exe=echo` will 
   then fail. The `exe` attribute could then become a `IGangaFile` object.
3. Combine 1. and 2. in the sense that we deprecate `Executable` and then create a new 
  application (`Program`?)  that get the behaviour of the updated `Executable`.

I am kind of in favour of option 2. but it gives some trouble in terms of schema evolution as the `exe` attribute will change type.

**Comment by alexanderrichards** [comment]
I also favour 2.

**Comment by egede** [comment]
@alexanderrichards  So what do we do with old `Executable` objects in the repositories of users. It is not just a schema migration from `File` objects to `IGangaFile` objects, but there are also some application objects (like the old `Hello World`) that will simply be broken.

**Comment by milliams** [comment]
@egede Curerntly, the XML stored for `Executable.exe` looks like one of the following:
```xml
<attribute name="exe"> 
  <value>'~/mychecker.py'</value>
</attribute>

<attribute name="exe"> 
  <value>File(name='/afs/cern.ch/user/m/mwilliam/mychecker.py',subdir='.')</value>
</attribute>
```
depending on whether it was set as a `str` or a `File`. If in a future Ganga version, `Executable.exe` was changed to be a `LocalFile` then perhaps, using the changes in #452 the `LocalFile` `__init__` could take either a string or a `File` and do the conversion there.

A potential problem is that there's currently no way to set a default *value* of a `ComponentItem` (as seen in #340), only a default type. Perhaps some `__init__` magic could fix this too though.

**Comment by alexanderrichards** [comment]
if the xml shows a `File` object then the conversion is a simple one as we know that they would be using the `Executable` object (in the new parlance) so we can presumably just substitute `LocalFile` for the `File` object.

In the first example, or I think any case where it's stored as a string we can probably convert to Command object. I think this should be safe (I'll think a little more about it) because in @milliams example they would have had to provide `mychecker.py` in the inputfiles anyway right? I think we only copy the Executable.exe into inputfiles automatically if it's the latter (a File object) case.

**Comment by drmarkwslater** [comment]
I think I may prefer option 3 because it's cleaner and more obvious. We can then control the phase out of `Executable` in a sensible way instead of changing it under people. I'm not particularly wedded to that though...

**Comment by egede** [comment]
@alexanderrichards When you say convert to `Command`, do you mean that the user will have to run some conversion script on their repository, or will this be something that happens the first time the lazy loading look at the object (and it would then declare it dirty and write the converted one)? The problem with the automatic conversion is that it can cause trouble for users that "try" the new version and then revert.

**Comment by egede** [comment]
@drmarkwslater If going for option 3, we need a good new name. I can think if `Script` or `Program` but I do not really fancy either.

**Comment by alexanderrichards** [comment]
> The problem with the automatic conversion is that it can cause trouble for users that "try" the new version and then revert.

Indeed, I withdraw my last comment.

**Comment by drmarkwslater** [comment]
@egede I quite liked `Program` actually 😄
