### ISSUE TITLE
Dataset returning proxied objects

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#480]
As @rob-c says in https://github.com/ganga-devs/ganga/pull/477/files/00cb2eae43ff1e5435d82b14425cdc26b90eac16#diff-cc8e6cb5a8320edcf320ba229bf84e2fR120, `Dataset` is returning proxied objects. This needs investigating as there should be nowhere that does this now.

**Comment by rob-c** [comment]
Just beet me I was writing an issue:

The following 2 commands (both behind the proxy layer and so shouldn't have proxied objects) don't give the same results in 6.1.20:

```
inputLFNs = ['LFN:'+this_file.lfn for this_file in wanted_job.inputdata if isType(this_file, DiracFile)]
```

```
inputLFNs = ['LFN:'+this_file.lfn for this_file in wanted_job.inputdata if instance(this_file, DiracFile)]
```

I suspect this is due to the GangaDataset object adding proxy to returned objects? (I'm not certain, I need to test that there isn't a proxied object being passed to the function).

This is occurring in RTHUtils:dirac_inputdata.

I'll run some stack traces and dump some objects to see if it sheds light as to what is going on here.

@milliams Should the Dataset objects be protected by the latest changes in the proxy code? If so I'll remove the addProxy statements in a quick PR and see if I can get that in quickly

**Comment by drmarkwslater** [comment]
The GangaDataset does indeed specifically add proxies to returned elements. This can now be changed I guess!

**Comment by rob-c** [comment]
@drmarkwslater I think I should change LHCbdataset as well so I'll happily change them.
