### ISSUE TITLE
IGangaFile and copies of jobs

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#484]
The other day I had a discussion with @alexanderrichards  about what we do with `IGangaFile` objects when a file is copied. We in general have (at least two problems).
1. Wildcards can be used in our name patterns. For outputfiles, these 
   might be populated when the job has finished leading to that the 
   wildcard is "resolved". However, when the job is copied, we want to 
   restore the wildcard. We solve this at the moment by the use of a list that contains the "real" files and then some special logic when the job is copied.
2. We (as in `Ganga` behind the scenes) sometimes add files to the list of `inputfiles` during the submit process. Examples are histogram files requested in `Gaudi` jobs within LHCb and the `exe` file in the current `Executable` application. This will come up for the new `Program` application as well.  At the moment this is solved through a mixture of ignoring the problem and creating special lists with these automatically added objects.

I wonder if this could be solved in a more elegant way by using the `hidden` and `copyable` schema attributes of `GangaObject`s. So for the two cases
1. The name with the wildcard is initially copyable and not hidden. When the output is resolved, the object with the wildcard is turned hidden but stay copyable. The resolved names on the other hand are not hidden and not copyable. When copied, we would have to "unhide"  the wildcard `IGangaFile`.
2. These objects we could just add to the list of inputfiles but they will be both hidden and not copyable. 

I do not know if it is possible to change the `copyable` and `hidden` attributes on an object-by-object level. The advantage of thjis idea is that the whole business turns into properties of the individual `IGangaFile` objects rather than relying on some external lists to manage the who thing.

Comments?

**Comment by rob-c** [comment]
My gut feeling is that we still haven't fully solved ```copyable``` and ```hidden``` wrt import/export of jobs, so I'm reluctant to trust the schema to do exactly what we want all the time. There are still a few gotchas in the proxy layer I think.

When you say ```resolved``` Do you mean that the ```resolved``` is that when you type ```job.outputfiles``` you see the wildcard resolved?
This is because the printer currently iterates over the subfiles but the full wildcard exists in the job summary.

Maybe if instead of deciding to copy the list of these files we ask each file (and each subfile) if it can be copied as a whole file between jobs? This just extends the current schema by 1 attribute. And/or we only ever copy the _parent_ file which has the globbable string or equivalent which possibly allows us to have a special namePattern for internal jobs (I'm less of a fan of this idea).

**Comment by egede** [comment]
@rob-c It might indeed be a bad idea to rely on the `copyable` and `hidden` attributes for this, but we can at least explore if we can make the decision to copy or not based on the individual file object and not on some list.

**Comment by rob-c** [comment]
I think something similar to ```is_static_object``` in the schema would be useful to represent to the parent object that we shouldn't copy it when making a copying of an object from in front of the Proxy.

(I'm tempted to say we can go as far as managing the prepared state file/directory this way when we look to remove File support and maybe improve SharedDir at some point in the future).
