### ISSUE TITLE
Fix/Remove _getWriteAccess and _getReadAccess in Objects.py

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#528]
We have recently had issues with these functions causing deadlocks (see #527, #510, #520). We should go over these specifically and the Registry in general to make sure that Objects only call into the registry when the absolutely have to (if they ever need to) and the registry locking is done in a bit more sensible way with read/write locks as @rob-c has suggested.

**Comment by rob-c** [comment]
@drmarkwslater I'm more keen to see these calls removed everywhere except the Objects class to begin with.
These calls used to be around to ensure objects were loaded and were used to workaround problems with the lazy-loading.

As we trust this works now I think we can/should remove all calls to get read/write access and setdirty that aren't in repos and/or the GangaObject/Node themselves.

I think we can move to get rid of them/rename them in the Objects as this would allow us to make it a lot clearer when an object is being loaded from disk.

The problem is that these functions do also get write access around a file when it's loaded from disk. I think it's sensible to keep these locks at least when we load an object from disk.
