### ISSUE TITLE
Monitoring and worker threads

### ISSUE THREAD

**Issue by rajanandakumar** [ganga-devs/ganga#56]
Hi,

It looks like the monitoring does not necessarily pick up the number of worker threads in the Ganga configuration (.gangarc). In my instance, I increased the number of worker threads to 10, but I have not seen more than 3 threads run at any given time - and to note, 3 is the default value of this parameter (NumWorkerThreads).

VO : LHCb
Ganga version : 6.1.13
OS : sl6

Of course the great use of increasing the number of threads is when I have a local machine with many cores, but which is not being used, I can hopefully increase the speed of all the operations possible with this.

Thanks and Cheers,
Raja.

**Comment by egede** [comment]
Hi Raja,

I suspect this is a misunderstanding between threads in Python and the 
pthreads in the underlying system.

When you start python, it runs as a single process with a single 
pthread. This is due to design choices in Python that makes it single 
threaded by nature as seen from the operating system. Thus everything 
will run on the same core.

The only way around this in Python is to spawn off new Python processes 
where you then communicate through pipes or something similar. This is 
done for the communication with Dirac (one for the interactive commands, 
one for the monitoring) and that is probably why you see three cores active.

The NumWorkerThreads controls the number of Python threads. This is 
useful to increase if there is a limit due to waiting for authentication 
from a server etc, as it can then use the local core more efficiently.

Cheers,
         Ulrik.

**Comment by rajanandakumar** [comment]
Hi Ulrik,

Thanks - I agree with your comment, but it kind of leaves me none the wiser in this case.

From what I see, for the "Ganga user threads" which do things like submit / resubmit - all the 10 threads are used when there is enough work to go around. So, for me there was a clear gain while submitting, to increase the number of threads to 10.

However, the "Ganga monitoring threads" are limited to 3 working at most (even though it lists 10 possible threads available now), even though I currently have about 250 jobs to be retrieved from the grid. I wonder what would have happened if I had reduced the NumWorkerThreads count to 2 or 1 - but I do not want to test now until my jobs are all downloaded and ntuples created.

Cheers,
Raja.

**Comment by rob-c** [comment]
@rajanandakumar the code which deals with the amount of available threads and queue-ing of tasks is the same for both the user and monitoring threads.

Are you seeing monitoring commands which have been queued and not run when there are many available monitoring threads?

I'm assuming that you're using the DIRAC backend? in which case the monitoring system is supposed to queue additional commands to be run on the monitoring threads which are exposed through the 'queues' command. These commands are constructed by the monitoring loop as it finds a job which needs updating.

If there are commands which have been queued and not running then there is a bug in the Monitoring queues system.

If there are simply not many commands being queued at once then this could be due to a bottleneck in the monitoring loop code. (This ganga job monitoring code is sometimes extremely slow when first starting up and when dealing with large numbers of (sub)jobs. As I've said I'm working on optimising this.)


I hope this clears things up a bit,

Thanks,

Rob

**Comment by rajanandakumar** [comment]
Hi Rob,

Thanks - indeed I am not seeing any queued monitoring commands which are waiting. So, this is then likely due to the bottleneck. Apologies for the noise - I will close this issue now and keep an eye on it when the next release is out.

Cheers,
Raja.
