### ISSUE TITLE
"ganga-install" script instead of "pip"

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#601]
It seems that the only way to properly install ganga from git is to use "pip".
I'm afraid that for many people this is NOT a feasible option at all.
Could you, please, give instructions how to download and setup ganga from git without requiring any fancy utilities (i.e. something that a regular user who has no administrator privileges and uses a "closed / cut down" system could use).
I guess the good old "ganga-install" script is doing it for "regular / official" ganga releases, so a "replacement" is needed for "git clone" downloaded ganga code.

**Comment by rob-c** [comment]
@JacekHoleczek does http://ganga.web.cern.ch/ganga/download/ganga-install work for you?

**Comment by rob-c** [comment]
http://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html

**Comment by rob-c** [comment]
I've installed ganga using pip in the past into my user area without any problems, are you having trouble installing pip or does `pip install ganga --user` not work for you for some reason?

**Comment by JacekHoleczek** [comment]
Yes, the "ganga-install" script works fine. But it cannot get the source code from git (it can only download and install "releases").
I cannot use "pip" because "pip" is NOT installed on the remote machine.
I don't think that I should try to install "pip" in my "${HOME}" as this may create problems for me later.

**Comment by rob-c** [comment]
There is no officially supported way of us distributing access to the latest develop branch on github. 
We are not technically (or officially) a rolling-release style project.

If you install ganga (in some way) you get the source code through doing this. Then all you have to do is replace the contents of the `ganga/python` folder with the `python` folder from github it should work but there is no sensible way for us to distribute access to this.

If you're asking can we look into re-enabling IPython 0.x support so you can use the project at some level after a `git clone` then this is possibly something I can look into but I don't think we can reasonably provide a script to get a working dev environment setup as it requires some manual configuration and we don't support systems which don't have some external python libraries installed, eg. stomp.py...

Due to our external dependence on python packages the recommended way is still to use `virtualenv` with `pip`.

**Comment by rob-c** [comment]
OK,

This worked for me and I'll update the twiki but I'm warning that this will probably break:

```
wget http://ganga.web.cern.ch/ganga/download/ganga-install
chmod +x ganga-install
./ganga-install 6.1.20
cd ~/Ganga/install
rm -fr 6.1.20
git clone https://github.com/ganga-devs/ganga
mv ganga 6.1.20
```

After this the ganga at `~/Ganga/install/6.1.20/bin/ganga` will be the version which is currently the latest code on github.

**Comment by JacekHoleczek** [comment]
Actually, one does not need to change the name of "ganga" into "6.12.0".
On my "SLC6" machine, I was able to get it working using:
```
wget http://ganga.web.cern.ch/ganga/download/ganga-install
python ganga-install --all-deps 6.1.20 # install the latest "release"
cd ${HOME}/Ganga/install
rm -rf 6.1.20 # get rid of the source code of the ganga "release"
git clone https://github.com/ganga-devs/ganga.git # download the "head"
cd
${HOME}/Ganga/install/ganga/bin/ganga # run the newly installed ganga
```

**Comment by milliams** [comment]
> Note: my point is NOT to re-enable IPython 0.x but to get an automatic way of downloading and installing all required dependencies, just like the "ganga-install" script is doing for regular "releases".

That is what `pip` is for. We might consider alternative installation methods in the future but for now, if you want to run the `develop` branch then you will have to a little more work than the average user.

**Comment by rob-c** [comment]
Given there are a few lines explaining what to do other then just `git clone` on read the docs I can close this issue

**Comment by alexanderrichards** [comment]
> I cannot use "pip" because "pip" is NOT installed on the remote machine.

FYI you don't need admin privilages to install pip to the users local area:

```bash
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
```
