### ISSUE TITLE
Files are copied to inputdir when not required

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#623]
When submitting a GaudiRun application (and quite possibly others), large files are copied from the shared area into the job specific inputdir. This is a waste of both file space and time. It should be ensured that files created in the inoutdir are truly files that are unique to the job in question. 

Due to the size of the files packed up for GaudiRun applications, the problem needs resolving soon.

**Comment by rob-c** [comment]
I don't think I see this for Dirac type jobs could this be due to the backend(s) doing this transfer. I've not looked into this much but yes we need to track this down and fix it.

**Comment by egede** [comment]
@rob-c Yes, I think the first step is to try to replicate the problem. I observed it together with Mark Whitehead when using `GaudiRun` for a `Local` job.

**Comment by mesmith75** [comment]
@egede Do you mean the copying of the cmake tar from the shared directory into the input sandbox tar? I see it on my local job too.

**Comment by egede** [comment]
@mesmith75 Yes indeed. We should trace down where that copy is happening. 

For the Interactive, Local and Batch backend (that all expect a shared filesystem) , the most optimal would actually be to unpack the tarball directly from the shared area (so not even copy it to the working directory of the job).

**Comment by mesmith75** [comment]
The files from the shared directory are being added to the input sandbox list in Ganga/GPIDev/Adapters/IBackend.py at about line 250:
            inputsandbox.extend(
                itertools.imap(lambda f: f.name, sharedir_files))
These are then included in the tar for the input sandbox files.

I'm not sure why this is only a problem for the GaudiRun app though for local running. Is the list of objects in the shared directory usually cleared?

**Comment by rob-c** [comment]
If the job is being submitted locally (or to a batch system).
I would naively expect that we can do away with adding them into the sandbox and simply inject a few lines of code into the script which is run on the WN to extract/copy the files there.
(Or copy them directly to the WN from a request on the WN)

Wouldn't it make more sense to copy all shared files to the WN if the WN has access to the files and then auto-extract any (supported) archives in the WN script? (`__jobscript__` on Localhost).
If we pass the path of the shared folder to the job directly then we can use some generic copy/extract command which can be shared between the various backends.

It may be a good idea to add a configurable option to the backend to preserve this old functionality if it's required for a backend such as condor or lcg (I'm not an expert on either of these).

This is now a _problem_ with GaudiRun as the contents of the shared directory is now potentially very large. Other applications make use of this but it's GaudiRun that is taxing the way this works.

**Comment by rob-c** [comment]
The shared directory should be cleared and removed when there are no longer any references in the `prep.metadata(0)` dict object. However I think we may have a problem with auto-cleaning/removing at least these folders as per a few users emails and an issue I've opened.

**Comment by egede** [comment]
> Wouldn't it make more sense to copy all shared files to the WN if the WN has access to the files and then auto-extract any (supported) archives in the WN script?

@rob-c While slightly less efficient than unpacking directly from the shared directory, I agree that this is more portable.

**Comment by egede** [comment]
> The shared directory should be cleared and removed ...

Irrelevant for this issue.

**Comment by mesmith75** [comment]
The cmake tar file gets added to the list of files in the input sandbox around line 200 of GaudiRunAppHandlers:
        if input_folders:
            raise ApplicationConfigurationError(None, 'Prepared folders not supported yet, please fix this in future')
        else:
            for f in input_files:
                input_sand.append(File(f))
These files come from the list of prepared files for the job.

The idea seems to be to include the options file which is first put into the shared dir into a tar for the job script - as a consequence everything from that directory gets copied over. It would probably be best to change it so that the options file is put straight into the input directory instead, or even better not copied at all and put into the tar file from its original location to save having two copies of it. That seems to work for the inputfile.
I stopped the cmake-input-sandbox.tgz being included by adding a check for the file type here and the job works fine.

**Comment by rob-c** [comment]
OK, best thing here is that the location of the file is recorded in the payload of the job rather than the file being sent to the input folder for each subjob.

The target file still _needs_ to be sent to the ganga prepared folder as this target is only important for the jobs which have been prepared and for keeping the prepared state. We shouldn't rely on this remaining on disk.
It doesn't need to be copied into each subjobs input folder. I thought this was happening to the master job per the original description.

Are the prepared folders already referenced/copied to the WN in this case? I've not explored this.

@mesmith75 https://guides.github.com/features/mastering-markdown/ is helpful for formatting on github :)

**Comment by mesmith75** [comment]
Added the check in and made pull request. #663

**Comment by mesmith75** [comment]
There also seems to be some duplication in the input dir for the Dirac backend. I'll look into that as well.

**Comment by rob-c** [comment]
This turned out to be a bug in `GaudiRun` (`GaudiExec`) are there any objections to closing this bug?
There is still the outstanding bug in cleaning up after DiracFiles which have been uploaded to the grid during a GaudiRun submit but this is a separate issue which isn't present in Core.
