### ISSUE TITLE
diracAPI does not work

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#674]
`diracAPI()` does not work with Ganga 6.1.22:

``` python
Ganga In [5]: diracAPI('print 5')
Ganga Out [5]: 'Traceback (most recent call last):\n  File "<stdin>", line 467, in <module>\n  File "<string>", line 453\n    print 5\n          ^\nSyntaxError: invalid syntax\n'
```

**Comment by rob-c** [comment]
@rmatev did this work with 6.1.20? do other commands work or are all commands through this broken?

**Comment by rmatev** [comment]
I just tried 6.1.20 and it doesn't work, too. But it might be just the documentation which is too old. The thing that made me stumble on this are calls like:
```
diracAPI("output(diraclhcb.bk.getRunsForFill(4555))")
```
with 6.1.22 it seems that all I need is to rename `diraclhcb` to `dirac`.

Here I'm relying on "internals", hence the fragility. It would be nice if the bookkeeping was properly exposed somehow.

**Comment by rob-c** [comment]
@rmatev Does `diracAPI("output(print 5)")` do anything sensible?

What is required of a book-keeping object if one were to be exposed? I imagine if there is a desire to fully expose (LHCb)Dirac object within Ganga we would need to write a Ganga layer to parse interactions in/out from the object due to the fact Dirac is quite isolated from the rest of Ganga.

**Comment by rmatev** [comment]
@rob-c no since it's not valid python:
```
Ganga In [2]: diracAPI('output(print 5)')
Ganga Out [2]: 'Traceback (most recent call last):\n  File "<stdin>", line 467, in <module>\n  File "<string>", line 453\n    output(print 5)\n                 ^\nSyntaxError: invalid syntax\n'
```
Ideally, you'll have the LHCbDirac object with all the help and so on. However, since there is the isolation of LHCbDirac, the only feasible layer would be something very lightweight, e.g.
```
def bkAPI(method, *args, **kwargs):
    diracAPI("output(dirac.bk.{}(*{!r}, **{!r}))".format(method, args, kwargs))
```

Can you remind me why LHCbDirac cannot be "mixed" with Ganga (for the LHCb ganga that is)?

**Comment by rob-c** [comment]
@rmatev We don't mix LHCbDirac (or DIRAC) with Ganga due to a few different reasons. The first is that both ourselves and DIRAC used to have conflicting external dependencies (this may or may not be the case at the moment I've not checked in a while myself). But in addition to this there are a large number of calls to DIRAC made by Ganga which can fail due to different reasons and when they do we prefer to have some wrapper to isolate Ganga from this a bit more to prevent the rest of Ganga having problems.

In principle I see any problem in exposing the book-keeping API the way that you suggest.
@egede Do you think this sounds like a sensible object to expose to the GPI for GangaLHCb?

**Comment by rob-c** [comment]
@rmatev The python code executed by the `diracAPI` has changed slightly. The expected output from the functions should always be wrapped in an `output` call as they're sent through a pipe which is parsed back within Ganga.
E.g. if you want to get `5` you need to do:
`diracAPI(output(5))` which will return 5
The stdout/stderr streams from the thread which is used to execute this code are (for the moment) pipped elsewhere and not exposed to the user.

I will look into re-enabling the stdout/stderr streams from the calls of `diracAPI` from within the Ganga GPI once I've finished some other tasks.

**Comment by rob-c** [comment]
Also I think the code expects the print function `print()` rather than the old print calls which I think explains your original error.

**Comment by mesmith75** [comment]
Works for me:
```python
[13:59:01]
Ganga In [5]: diracAPI('getReplicas("/lhcb/MC/2012/ALLSTREAMS.DST/00032303/0000/00032303_00000013_1.allstreams.dst")')
Ganga Out [5]: 
{'Failed': {},
 'Successful': {'/lhcb/MC/2012/ALLSTREAMS.DST/00032303/0000/00032303_00000013_1.allstreams.dst': {'CERN_MC-DST-EOS': 'srm://srm-eoslhcb.cern.ch:8443/srm/v2/server?SFN=/eos/lhcb/grid/prod/lhcb/MC/2012/ALLSTREAMS.DST/00032303/0000/00032303_00000013_1.allstreams.dst',
   'Manchester_MC-DST': 'srm://bohr3226.tier2.hep.manchester.ac.uk:8446/srm/managerv2?SFN=/dpm/tier2.hep.manchester.ac.uk/home/lhcb/lhcb/MC/2012/ALLSTREAMS.DST/00032303/0000/00032303_00000013_1.allstreams.dst'}}}
```
