### ISSUE TITLE
Schema version checking

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#70]
Whenever we define a new `GangaObject` subclass we have to also give it a `_schema` data member with an appropriate `Version` argument. As far as I can tell, the only place this version is used is in the VStreamer parsing at https://github.com/ganga-devs/ganga/blob/0b796886d15f843d38e1a85bbb6078f0677dca93/python/Ganga/Core/GangaRepository/VStreamer.py#L311 where it will create a dummy object if the versions don't match. I'm wondering how much we _actually_ use this feature and whether it's worth the effort of having to define a `Version` in every `GangaObject`? I assume the idea is supposed to be that the minor version is increased for every addition to the schema and the major version is increased for every removal.

Looking at `Job` however shows that in 5 years, between [here](https://github.com/ganga-devs/ganga/blob/9c227446c18742684e2abd8fc9160e22c650e2eb/python/Ganga/GPIDev/Lib/Job/Job.py#L104) and [here](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Lib/Job/Job.py#L172) there were lots of additions made but the version did not increase once. If we _had_ have increased the version number then loading a new job in an old Ganga would fail.

At present, if we load a new job with an old Ganga and then again with a new Ganga then information is lost (e.g. setting `parallel_submit=True` on a `Job` in 6.1.13, loading it with 6.0.44 and then again with 6.1.13 resets it to `False`).

I'm not sure how to fix this or even if we need to? If we remove a schema attribute between version then it seems that it is just silently ignored when loading and if we add a new one then it seems to just use the default value. If this is the case and we're ok with it then I suggest removing the version checking entirely. Perhaps we print a warning if loading a job with new/removed attributes?

**Comment by egede** [comment]
The schema version I guess would allow you to change the type of information stored for a given attribute or change how it is stored. In that sense, it could come in useful for how @rob-c wants to change the storage for Dataset objects. For deletions/additions, the present way of dealing with things is fine, but I would be cautious about deleting this feature.

**Comment by rob-c** [comment]
Hi all, I've been giving this some thought, apologies but I've made a few drafts of this message already and it gets difficult to sort out.

##### Problem

The problem is that ```isCompatible``` function is a tad aggressive with backwards compatibility imo.
We don't want to cause a job not to be backwards compatible due to some extra config or metadata being lost imo, but we also don't want to lose this information if we can help it.


If a schema is loaded and the object on disk has extra information this information is being destroyed by the fact that this is not stored within the schema.

However, I still think a sensible thing is to lock older/newer jobs on disk in 6.1.15 if we cannot load/modify them. I strongly think we should consider bumping some hard versions come Ganga 6.2 to try and enforce a forward only move if it's needed.
I tried doing this with 6.1 but there were technical reasons why I decided not to go down this route.

A more helpful error such as 'please use an older/newer (as appropriate) version of Ganga to modify this job' when we can't load a job would be nice.


##### After looking at the ```isCompatible``` function:

I think that we should change this to support minor version changes and define these as changes  which should NOT cause the job to become un-loadable by earlier versions of the Schema.
Also, we should continue to should not support major version changes which could potentially be a complete rewrite of the class and/or schema.
If a schema is changed in future such that loading the job will cause the XML structure to change then this should always be a major change imo. I can't think of a good reason why we would need more than major and minor version increments.


##### Proposed solution
Firstly I think we need to encourage developers to use these more and one barrier to this is we're lacking the ability to load 'newer' semi-compatible jobs with 'older' schema versions of Ganga imo.

It would be nice to store any (unknown)extra schema attributes in a read-only dictionary within the schema which is stored and re-written to disk along with any possible future changes to the job.
(and of course un-copyable so this is lost when the job is finally destroyed)
This is very possible but it requires some work to be done with the ```Schema``` and ```GangaObject::append``` functions within the Core.

*Unfortunately, this is completely incompatible with the ```is_prepared``` property for applications but this is a problem for another day and in another issue...*

##### Aside:

I know it's only an example but to be completely honest I'd really like 6.1.14/15 to be released so that people will stop talking about 6.0.44 as maintaining this as well now is just not feasible for much longer.

##### addendum

@egede Yes this is potentially a major change here as ideally old jobs would be modified in such a way that old versions of code couldn't read the XML...
I'd like to re-structure some of the XML handling code to potentially allow for some 'easy' migration tools to be written in the future.
I would like to be able to load older jobs with a dataset generator to bring the advantage to older jobs but doing this could take a lot of development time which may be easily mitigated by encouraging users to update and resubmit.

**Comment by alexanderrichards** [comment]
Hi just my two cents worth but like Matt I saw no reason to keep the version information so did away with it in some of the rewritten stuff I've been playing with. If upon loading an object there is an error due to a missing attribute or having specified that the attribute is a different type then this is caught at load time and presented to the user as an incompatibility. I didn't see the need to retain extra version number information for what is essentially a does it load or not boolean.

**Comment by rob-c** [comment]
Hmm, this concerns me a little.

I've written down some more thoughts on this I'll put in the following post but I'm more in favour of keeping the Version information as a way of knowing if a schema is compatible.
Yes, we can manually inspect the Schema but this starts to get very confusing very quickly over a simple integer check for compatibility imo.

I'd like to raise this topic for discussion in tomorrows meeting if possible?

**Comment by rob-c** [comment]
We have several different problems with this system which should always be dealt with differently.

1. Objects on disk are a subset of what is required by the Schema.
I think in this case correct behaviour is that we load the object and populate the missing data with default values.
 * How do we know that these values reproduce the behaviour we expected if the Job was constructed before this configurable was available?

2. Objects on disk are a superset of what is required by the Schema.
 * Currently the object is just loaded if the version is the same.
 * I think what we should be doing is taking the extra data from disk and making sure it's stored with the object for when it's modified and written to disk again.
 * Currently this information is destroyed as per @milliams observations.

3. **How do we know if it's safe to load a job if the Schema has changed?**

4. If we assume the Schema is always compatible with the information stored on disk then we should be explicitly allowed to load it for monitoring etc:
 * Is this extra information just extra configurables/options not used by this instance of the object?
 * Does this change effect a relatively cosmetic issue (e.g. parallel_submit) or does this change represent a bigger change such as inputfiles vs inputdata?

5. If we explicitly define that any change in the Schema are non-compatible should we lock the job and warn the user?
 * This now means users aren't be able to load a job that has been created in a newer version of Ganga when they downgrade. (This happens a LOT atm)
 * This also means newer versions of Ganga can't load older jobs just due to adding a new feature to the Schema. This means jobs have to be monitored with the version of Ganga that created them.


I apologise if these examples appear crude but they are questions that I think crop up if we don't have some way of knowing if an object has changed in a forwards/backwards incompatible way:


##### Bad example:
There is an external API change for some external service in handling new jobs, but all old jobs need to be correctly handled and updated through the monitoring system.

The old/new Jobs explicitly define their behaviour on some changed part of the external API, how can we tell that the job is compatible if the schema doesn't change? (e.g. something like where output is stored or protocols used for some communication)
If we load and mangle the job with the new API then we could potentially destroy the old job information with no way to revert, is this a good thing?

e.g:
1. myApp in Ganga v7r1 creates a job which requires a certain application configurable to know where data is. The default value corresponds to eos.
2. myApp in Ganga v7r2 no longer supports eos but the schema exposed to the user doesn't know this.
3. myApp from Ganga v7r1 is loaded with v7r2 and fails due to now being able to cope with eos storage.
4. Ganga v7r2 writes the job back to disk and Ganga v7r1 now has a problem loading the job correctly due to some minor schema change.

(I know the solution would be to store this information within the schema but what if we never expected to change this when constructing the Schema?)

##### Another problem:

If the schema is assumed to be compatible:

1. Ganga v7r1 creates a job
2. Ganga v7r2 loads the job and appends the schema and writes it to disk
3. Ganga v7r1 is now used by the user because they didn't/couldn't use v7r2. How does Ganga v7r1 know what the changed Schema is compatible?
4. Ganga v7r1 attempts to load a newer job from Ganga v7r2 and mangles the job as the new schema attribute changed how other objects in the schema are used.

If the schema change is assumed to be non compatible:

1. Ganga v7r1p0 creates a job
2. Ganga v7r1p1 modified the job definition to allow for the user to configure some behaviour.
3. Ganga v7r1p1 cannot load a job from Ganga v7r1p0 even though Ganga v7r1p0 is being deprecated and has a known bug.
4. After many cycles of this users don't know which version of Ganga is safe to use.

**Comment by alexanderrichards** [comment]
@rob-c There are a lot of cases there and a lot to take in but I'll try and address them

> `1.` Objects on disk are a subset of what is required by the Schema.

In this case as you say we would load the object and the load would succeed as all attributes would load properly and defaults would naturally fill the rest. It is then an option we have to compare how many we loaded to how many there should be and warn the user of the new defaults.

> `2.` Objects on disk are a superset of what is required by the Schema.

Without the version information I would foresee that this would fail as an attribute read from disk could not be set on the current object  so loading fails and the user is warned. This object is incompatible with the new version and the user is told they cannot load this object. This I think makes sense as there is clearly extra information that the new version doesn't know how to handle as so cannot guarantee that the object will be treated the same as it was in the old version.

> `3.` How do we know if it's safe to load a job if the Schema has changed?

If it loads it's safe. This means that the onus is on tightening up the schema attributes themselves. This can include adding a list of allowed types/values.


> `4.` If we assume the Schema is always compatible with the information stored on disk then we should be explicitly allowed to load it for monitoring etc:

I'm afraid I didn't fully understand this. I would say we never assume that an object on disk is compatible and as above if it loads then it is compatible.


> `5.` If we explicitly define that any change in the Schema are non-compatible should we lock the job and warn the user?

I don't think that we explicitly define this for example if my attribute is defined as taking the values 'a' and 'b' and then I change the schema to allow 'a', 'b' and 'c' then this new schema will load the old object perfectly well and it's compatible.


> __Bad example__
> e.g:
> 1. myApp in Ganga v7r1 creates a job which requires a certain application configurable to know where data is. The default value corresponds to eos.
> 2. myApp in Ganga v7r2 no longer supports eos but the schema exposed to the user doesn't know this.
> 3. myApp from Ganga v7r1 is loaded with v7r2 and fails due to now being able to cope with eos storage.
> 4. Ganga v7r2 writes the job back to disk and Ganga v7r1 now has a problem loading the job correctly due to some minor schema change.

In this case as step 2 when the object is being loaded it will fail as eos is no longer valid. so this object is incompatible and will not load in the new version which I think is what we want as it is true that eos is not valid.


> If the schema is assumed to be compatible:
> 
>     Ganga v7r1 creates a job
>     Ganga v7r2 loads the job and appends the schema and writes it to disk
>     Ganga v7r1 is now used by the user because they didn't/couldn't use v7r2. How does Ganga v7r1 know what the changed Schema is compatible?
>     Ganga v7r1 attempts to load a newer job from Ganga v7r2 and mangles the job as the new schema attribute changed how other objects in the schema are used.

In this case if the new schema from v7r2 is incompatible with v7r1 it will not load in the old version.  if it is then it will load.


> If the schema change is assumed to be non compatible:
> 
>     Ganga v7r1p0 creates a job
>     Ganga v7r1p1 modified the job definition to allow for the user to configure some behaviour.
>     Ganga v7r1p1 cannot load a job from Ganga v7r1p0 even though Ganga v7r1p0 is being deprecated and has a known bug.
>     After many cycles of this users don't know which version of Ganga is safe to use.

Sorry I don't understand this one. if v7r1p1 loads and modifies the job (which amounts to adding defaults to missing items.) then it has loaded the job from v7r1p0

As you say we can discuss this at the dev meeting
Cheers
Alex

**Comment by alexanderrichards** [comment]
I guess what it boils down to from my point of view is that if you have a version number you have either one of two scenarios

1. you have a policy of which version numbers you will allow to be loaded (e.g. nothing older than a major version). This is artificial and the object might have actually loaded fine if the only schema change was to add new items or include allowed values. To make this number meaningful then you have to remember what is a safe compatibility when updating the version number as well as what minor/major version you can update it to for any given schema change.

2. you allow certain objects to be loaded based on some (your own or groups) knowledge of it being ok based on that number. This is not very stable as it relies on external knowledge and may mean knowing different safe version numbers for different objects.


Far better I'd say to try and load the object and if it cant load an object type or there is a missing schema attribute or the value is no longer valid then tell the user it's invalid.

After all the version numbers are only used as a guide as to whether to load or not. If we decide based on version number that the object are incompatible then this would have been the outcome of trying to load it anyway. If we decide to load it based on version number then presumably it would have loaded anyway as it was just an additional schema attribute which would be defaulted or an extra allowed value. This is what I meant by essentially a boolean as you still have to attempt the loading after you have made the version based decision.

**Comment by rob-c** [comment]
OK, if we're loading objects from disk with extra information we need a mechanism for preserving this data in a read-only manner.
This should be something we agree on so I'll assume this to be true.

As for the safety, major != safe, minor == safe, I don't know why this is so bad, tbh, we can even drop the minor here if we build in a backwards compatible way of preserving data.
'
'
In fact I'd like to propose we fix preserving information not known to the current schema and keep the major version information to resolve compatibility issues and drop the minor version support as this serves no useful purpose if the job is compatible. As controversial as this may be.

'
'
I'll explain my concerns wrt compatibility below:


My problem with dropping all version checking is that that the only check that is performed when loading an attribute into memory is to test the type against the allowed types in the schema def.
If the class wants/needs to change the contents of the object which is stored then there is no sensible way to add support for this unless we have every class do the checking itself which largely does away with the whole point of schema system.

I know that statement is probably a bit strong but if the class can't write 'supercali...' to where it used to write 'foo:bar' then there is no easy way to convey that the expectations of the class have changed.

Yes the class can add a new attribute then we end up with 'stale' schema attributes which aren't being used or are only required for loading old jobs through ganga.
This leaves the schema cluttered and confusing which I'm not in favour of.

Also when an older object is loaded and manipulated it is always written with the version of the schema used at runtime so future Ganga versions would always upgrade an object potentially into a format that cannot be read by older versions.

eg:

Ganga v7r1 stores the attribute {myData, myGangaClassv1}
Ganga v7r2 can read myGangaClassv1 but now has myGangaClassv2. It can also translate the classes to the newer and better myGangaClassv2 which is largely a superset of myGangaClassv2 but is different enough to not be backwards compatible.

user now creates a job in v7r1, tries out v7r2 and doesn't like it and now attempts to go back to v7r1.

The job they created in 7r1 now has the attribute {myData, myGangaClassv2} which causes all jobs to now not be accessible.
The user cannot use v7r2 due to a new bug or other incompatibility and cannot use v7r1 due to the fact that their jobs have now been mangled by Ganga v7r2 which could read them.
The problem is that Ganga v7r2 has a very good reason to be using myGangaClassv2 because it addresses an issue.

I would like a major version number to allow us to ask the user if they want the object to be upgraded/loaded to prevent occurrences such as this.

**Comment by egede** [comment]
We have managed to live for a very long time without any issues caused my careful schema evolution. Seems obvious to me that the cure is worse than the disease.
