### ISSUE TITLE
SplitByFiles GangaList datatype ignored

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#727]
There looks to be a bug in SplitByFiles:
https://github.com/ganga-devs/ganga/blob/develop/python/GangaLHCb/Lib/Splitters/SplitByFiles.py#L88

If the dataset type is a GangaList this isType function doesn't see it - I think because of the parentheses - so the splitting doesn't work. Removing them seems to get it to work. Is that correct?

**Comment by alexanderrichards** [comment]
yes it should be comparing to the *type* `GangaList` rather than an instance thereof presumably. However this would be better written with the `isinstance` python builtin.

One question I have that arises from this bug as well as #521 is how come these things are not picked up in the testing? Particularly with #521 as I believe that the default `Executable` application has args with it and therefore presumably would not have succeeded?

**Comment by rob-c** [comment]
I think `isinstance` should now be safe to use now as the proxy is always correctly stripped.
(The `isType` was supposed to detect instances and take a `type` of the object, but it's probably better to fix the code to be more readable regardless and this is probably failing.)
@alexanderrichards I think this is using an LHCb splitter which isn't currently being tested in the automated tests. We should probably add a test for this...
