### ISSUE TITLE
Fast accessURL on many Dirac files

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#738]
`DiracFile.accessURL` is great, but way too slow (~8 s). I often have jobs with few hundred subjobs. If I call `.accessURL()` on the output file of each subjob, it will take O(hour) to get all the urls, which is unacceptable.

My solution to this was to make one Dirac call for many files:

``` python
from GangaDirac.Lib.Utilities.DiracUtilities import execute
opts = '--Protocol xroot,root'
cmd = 'dirac-dms-lfn-accessURL {} {}'.format(','.join(lfns), opts)
output = execute(cmd, shell=True)
```

Unfortunately, this is broken in 6.1.22 (and 6.1.24), MWE:

``` python
[22:42:41]
Ganga In [6]: from GangaDirac.Lib.Utilities.DiracUtilities import execute

[22:42:46]
Ganga In [7]: execute('dirac-dms-lfn-accessURL /lhcb/user/r/rmatev/2016_08/136797/136797530/ntuples.root', shell=True)
ERROR    Error: insecure string pickle
ERROR    Unknown/Unexpected ERROR!!
...
ValueError: insecure string pickle
```

I'd appreciate a lot any workarounds as well as a proper longer term solution.

**Comment by rmatev** [comment]
And of course I don't need ganga's execute in this case. It can be replaced by
```python
subprocess.check_output(['lb-run', 'LHCbDirac/latest', 'dirac-dms-lfn-accessURL', '/lhcb/user/r/rmatev/2016_08/136797/136797530/ntuples.root'])
```

The question about a proper solution still holds.

**Comment by mesmith75** [comment]
You make a good point about the time. I think it is because ganga looks up the list of locations for the DiracFile and then gets the accessURL for a specified location picked from the list. Both of these things take a little time.

We can certainly come up with a function in ganga to give you the accessURLs from a list of LFNs.
As you point out that functionality exists with LHCbDirac. You can download a list of LFNs into a text file from Ganga:
```python
J = 1017
j=jobs(J)
thefile = open(str(J)+"_LFNs.txt",'w')
ds = []
for js in j.subjobs:
     if js.status=='completed':
         thefile.write("%s\n" % js.backend.getOutputDataLFNs()[0])
thefile.close()
```
And then point dirac-dms-lfn-accessURL to it:
```
dirac-dms-lfn-accessURL < 1017_LFNs.txt
```

Of course you might end up with two URLs for the same file if it has been replicated. I'll take another look with Ganga in the morning.

**Comment by rmatev** [comment]
Thanks for looking. If that helps, here's my function that calls and parses the output of `dirac-dms-lfn-accessURL`: https://github.com/rmatev/ganga-tools/blob/master/gutils/download.py#L65

It is quite ugly to do it with the command, but IIRC, the Dirac API did not expose something similar enough.

**Comment by mesmith75** [comment]
Unfortunately the DiracAPI doesn't quite do what we want. You can give ```getReplicas``` a list of lfns. You can also give ```getAccessURL``` a list of LFNs but you have to also give it a single valid SE.

So what we can do is make a list of the unique SEs that the files in the list are at:
```python
#get all the replicas:
reps = execute('getReplicas(%s)' %lfns)
#Get the SEs
SEs = []
for lf in reps['Value']['Successful']:
    thisSE = reps['Value']['Successful'][lf].values()
    if thisSE in SEs:
        continue
    else:
        SEs.append(thisSE)
```
The we iterate over this list of SEs with the getAccessURL and avoid doing it twice for the same LFN:
```python
processedLFNs = []
myURLs = []
for SE in SEs:
         thisSEFiles = execute('getAccessURL(%s, "%s")' % (lfns , 'CERN-USER'))['Value']['Successful']
            for file in thisSEFiles.keys():
                 if file in processedLFNs:
                     continue
                 else:
                   myURLs.append(thisSEFiles[file])
```

It is not quite ideal because it still has to run a Dirac command for each SE but it should be a lot quicker than previously as I assume there are far fewer SEs than files.

Your solution with dirac-dms-lfn-accessURL is probably the quickest in terms of speed but this saves having to mess around with formatting command line output.

**Comment by mesmith75** [comment]
I think this should be added to the Dirac backend so one can just do something like j.getAccessURLs() and get all the files for the job (including subjobs).

**Comment by rob-c** [comment]
@mesmith75 Sounds like a nice feature to have. I'm assuming it would run over all completed subjobs regardless of if they completed successfully or not?

**Comment by mesmith75** [comment]
Maybe the last part would be better to remove the processed lfn:
```python
for SE in SEs:
        thisSEFiles = execute('getAccessURL(%s, "%s")' % (lfns , SE))['Value']['Successful']
        for file in thisSEFiles.keys():
             processedLFNs.append(file)
             myURLs.append(thisSEFiles[file])
             lfns.remove(file)
```
@rob-c I guess it should be over just the successful ones other wise there will be lots of errors with missing files?

**Comment by rob-c** [comment]
Maybe some static function which takes a list of DiracFiles would be useful?
Placing a helper method on the backend which passses this the _good_ files from the job would be helpful but allows users to pass whatever files they want to some static method

**Comment by mesmith75** [comment]
Yes that sounds good.

**Comment by mesmith75** [comment]
@rob-c Where would be the best place to put the static function. I assume the helper method goes in DiracBase?

**Comment by mesmith75** [comment]
Implemented in #801

**Comment by rmatev** [comment]
Quite a few people are using the already existing `accessURL`, so it would be nice to advertise the new feature widely so they can switch.

**Comment by mesmith75** [comment]
Yes we will do. This is for the next release which is a major features upgrade so I'll advertise then. It should be out in a week or two. Sorry for the delay.
