### ISSUE TITLE
ganga 6.1.24's condor job not running on USTC's cluster ui01.lcg.ustc.edu.cn

### ISSUE THREAD

**Issue by RongkunWang** [ganga-devs/ganga#741]
So, I used 
/cvmfs/ganga.cern.ch/Ganga/install/ganga/bin/ganga athena --condor --nocompile --inputtype Local --split=60  \
      --inPfnListFile $DATASETS  \
      --outputlocation="/lustre/AtlUser/rkwang/NTUP4L_HZdZd/condor.$DATE.signal_13TeV_fastSim_mc15c"  \
      --outputtype 'ATLAS' share/analysisJobOptions.py
to upload the job to condor.

with 2.4.18 AthAnalysisBase.

And then when I opened ganga, it will have this message appearing again and again:
**ERROR    Monitoring Error: local variable 'exitLine' referenced before assignment**

In stdout, there's no sign of ATHENA running(no INFO output etc.)

there's no messages such as "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/AtlasSetup/V00-07-39/AtlasSetup/scripts/asetup.sh AthAnalysisBase,2.4.18,64,here --cmtconfig=x86_64-slc6-gcc49-opt"  informing athena is being setup.

And at the end of the stdout:

\-------------------
getstats called ...
ERROR : DATASETTYPE not defined, using DQ2_LOCAL
{}
getstats finished...
\-------------------

Exit code: 32512

**Comment by drmarkwslater** [comment]
@RongkunWang I would very much recommend using the version of Ganga deployed by Atlas rather than the vanilla version. If you do:
```
setupATLAS
<setup Athena>
lsetup ganga
ganga athena ....
```

And you should hopefully have more luck! If not, let me know and I'll have a look.

**Comment by RongkunWang** [comment]
Thanks Mark. It's running now, but I still have the error when I try to monitor it:
ERROR    Monitoring Error: local variable 'exitLine' referenced before assignment.

what could be the source of this problem?

**Comment by RongkunWang** [comment]
Oh, I got this: 

Py:ConfigurableDb    INFO Read module info for 618 configurables from 3 genConfDb files
Py:ConfigurableDb    INFO No duplicates have been found: that's good !
Shortened traceback (most recent user call last):
 IncludeError: include file analysisJobOptions.py can not be found
Py:Athena            INFO leaving with code 2: "an error occurred when including a file"
...
Exit code: 512

**Comment by drmarkwslater** [comment]
@RongkunWang So the `exitLine` problem is a legit bug but it's actually pointing to an issue with the Condor setup as it will only happen if the stdout file is there but is empty when Ganga tries to look at it. I'll try to think of a way to properly figure out what the problem is this weekend.

The problem of not finding the job options is a bit strange. I'll have a think about that as well...

**Comment by RongkunWang** [comment]
Thanks Mark. So the path to the job option is a relative path from the dir that I submit my job, is that ok?

**Comment by drmarkwslater** [comment]
It should be and if it's not, I'll fix it so it is 😄

**Comment by drmarkwslater** [comment]
@RongkunWang So I think I've figured out what the problem is - I believe that Ganga is seeing that the job has finished from Condor and immediately checks for the stdout file. However, for some reason the stdout file is present but empty and so it fails when trying to check the status of the job. Just to confirm this, could you do answer the following?

1) Are the stdout files that are created in the gangadir? i.e. are they under `~/gangdir/workspace/<UID>/LocalXML/<JID>/output/`?

2) What filesystem is your home area mounted on? Basically, do this:
```
mount | grep `readlink -m ~/../../`
```
and let me know the 'type' that is output (no need to paste the whole output!).

Assuming this is the problem I'll try to get a fix ready today. I'll also have a look at the JOs issue as well.

**Comment by RongkunWang** [comment]
Hi, Mark. 

> 1) Are the stdout files that are created in the gangadir?

Yes, I can see them in the gangadir. I derive the error messages from there.

> 2) What filesystem is your home area mounted on?

My home is mounted on nfs system, (rw, nosuid,soft...)

Thanks.

**Comment by drmarkwslater** [comment]
Thanks! I'm a bit surprised that an NFS system is being that slow to update (I would have expected it from AFS 😄 ) but nevermind. I'll put a patch together for you to try and we'll see if that works. Just to eliminate ATLAS from this part of the problem, could you run Ganga with a clean gangadir (just move your old one away for the moment) and do the following:
```
j = Job()
j.backend = Condor()
j.submit()
```
You should hopefully see the same errors and these should then stop after a while and the job go to completed.

**Comment by drmarkwslater** [comment]
@RongkunWang So the missing JOs problem is a definite bug which I'll fix in the next 24 hours. To get around it, simply submit your job from either the `share` dir or the root directory of your Test Area and you should be OK!

**Comment by RongkunWang** [comment]
Thanks, Mark.

The jobs' running now with uploading from Test Area.

As for the first comment, yes, the error didn't appear again (before that, the error sometimes is 'failed to retrieve job status', something like that, wording is not exact.)
