### ISSUE TITLE
Nighlies not running Core tests against the plugins

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#769]
I'm going through the nightlies tests and seeing that the Core tests aren't being run against the various plugins.

I see there is the comment:

```
 However, this breaks because it can't merge the results properly.
```

Is it understood what is broken here as I'm keen to re-run the nightly tests in this way to catch any potential problems in the future.

**Comment by drmarkwslater** [comment]
Basically, if you run the tests as it was done, you either get the same `.xml` files created for the two sets of Core tests or because the tests are covered twice it goes wrong in the merge. Either way, as it stands, it doesn't work and you'll need to run these by hand yourself for the moment until we can figure out a way round that.

**Comment by rob-c** [comment]
OK, I'll have a quick look and see if there is any way I can get this to work. Does the failure to merge the XML register as a failure within Jenkins plugin reading these XML files or is this happening within py.test?

**Comment by rob-c** [comment]
https://github.com/miki725/xunitmerge looks like it could potentially be helpful for this

**Comment by milliams** [comment]
I honestly don't think that this is the way we want to do it anyway. All it does is increase the number of combinations we have to test. If you're worried that the LHCb configuration will conflict with the running of the Core tests then I suggest creating a separate nightly job called LHCbNightly or something and test it there.

**Comment by rob-c** [comment]
@milliams This showed at least 1 or 2 bugs in the past and helps keep the tests clear in what they expect imo.
If the test shouldn't fail because it's being run in a config it was never intended to be run in it should be skipped imo.
Having the requirement that the tests all run in all configs lowers some barrier to knowing what is going wrong, else someone coming along in the future may setup an LHCb config and see a load of tests fail in the Core and wonder why this is. I strongly feel this is no better than the old test system.
As for resource costs these nightly tests should be run on a dedicated box overnight when we don't care about it taking 20min or 4 hours.

**Comment by milliams** [comment]
The problem is that looking at https://ganga-ci.cern.ch/jenkins/job/Nightly/430/, it's almost impossible to know *which* version of `TestLCG` failed; the normal one or one run with some other plugin/config loaded. Having a NightlyLHCbConfig test (or something which is named cleverly, perhaps using Jenking subjobs to parametrise it) allows the test failures to be useful.
