### ISSUE TITLE
Check that j.peek() on Dirac is doing what it should

### ISSUE THREAD

**Issue by MannyMoo** [ganga-devs/ganga#885]
Often it just returns
"Watchdog is initializing and will attempt to obtain standard output from application thread"
while other times it does return some stdout. 

Looking in GangaDirac/Lib/Server/DiracCommands.py, it seems just to use dirac.peek(id), which I suspect is the same as using dirac-wms-job-peek, so maybe it's more on the Dirac side, but should be checked that it's implemented correctly.

**Comment by rob-c** [comment]
This is correctly implemented within Ganga and is an issue to do with either DIRAC caching stdout in it's support for various backends or it's the backend not updating the information due to a configuration issue at the site.
This is highly unlikely something which can be addressed within Ganga using the DIRAC API as this also happens on the interactive web interface for DIRAC jobs.

I would suggest taking note of which sites this happens for so you can work out what service they're running and then ask the DIRAC devs if they can have a look at this. This has cropped up before on the GridPP DIRAC instance as well with some sites but I forget the configurations which led to this happening exactly.

**Comment by MannyMoo** [comment]
OK, thanks for the confirmation. I'll take it up on the Dirac side.
