### ISSUE TITLE
Improve messages when quitting and the monitoring is busy

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#889]
When I quit ganga while it's still running the monitoring in the background I get messages like the ones below. I presume that sticking to the defaults ("no" for the first and "yes" for the second) is safe. However, it would be nice to tell more about what "force" and "purge" mean and what are the implications of not following the suggestion.

```
Job status update or output download still in progress (shutdown not completed after 5 seconds). 1 background thread(s) still running: ['MonitoringWorker_3_1480619834980']. Do you want to force the exit (y/[n])?
Monitoring queue contains unfinished tasks:
['Job 121.13 Finalizing', 'Job 121.6 Finalizing', 'Job 121.14 Finalizing', 'Job 121.4 Finalizing', 'Job 121.7 Finalizing', 'Job 121.11 Finalizing', 'Job 121.10 Finalizing', 'Job 121.1 Finalizing', 'Job 121.8 Finalizing', 'Job 121.0 Finalizing', 'Job 121.9 Finalizing', 'Job 121.2 Finalizing', 'Job 121.5 Finalizing', 'Job 121.3 Finalizing', 'Job 121.12 Finalizing']
Do you want to Purge the monitoring queue ([y]/n):
```

**Comment by rob-c** [comment]
I think we can look into removing the first method (The monitoring can _always_ be asked to finish safely now due to the fact the queues ask if the user wants to purge them.
Given these will __always__ startup in the future of Ganga now is there any harm in just clearning the list of pending tasks on default now? This was useful to know in the past when Ganga was being much slower but heading toward 6.2/6.3 is it a good idea to just inform the user of the non-pending tasks which are now running and that they may take a few seconds?

**Comment by egede** [comment]
@rob-c To clear the list of pending tasks on quitting seems quite reasonable to me. So should the order be that you purge the queue, and then if things have not finished within a few seconds, you ask the standard question about forcing the exit. To completely take away the force exit message I think is a bad idea.

**Comment by rob-c** [comment]
@egede Apologies, that message was formed as I was typing. I think it would be a good idea to allow the user to 'force' the exit. But I think we can safely move this into the queue stage of the shutdown code rather than elsewhere as this is the section of code which holds up the shutdown and makes everything a bit more difficult.
As all pending work is on a `GangaThread` we can just issue a message from the thread manager to the effect of:
```
Ganga is still busy doing tasks:
.....
Should we force an exit or wait? [y]/n
``` which would be a bit clearer about the implications of what is going on

**Comment by egede** [comment]
@rob-c I like the message that tells what Ganga is busy with. Can that be kept?

**Comment by rob-c** [comment]
We could keep it but I wonder should we only prompt once? If users are in a rush to close ganga and go away and do something they don't likely want to be prompted that tasks are pending.
Should this be reduced to a summary then similar to:
```
Ganga is still busy doing some work:
[Tasks Pending]
...
[Tasks Running]
...
Should we:
  Clear queues and retry shutting down [1],
  Force the exit of Ganga now [2],
  or Wait for pending tasks to all complete [3]?
( [1]/2/3 ):
```

I'm wondering if the option to clear the pending tasks and shutdown is a sensible option. I liked it, it allows for the cleanest shutdown of ganga without waiting for it to parse all ~hundred pending jobs to be finalized.

**Comment by egede** [comment]
@egede I think the repeated asking is actually OK, but do something like asking once after a short time and then subsequently after quite a bit longer. Maybe 10 s first time and then once a minute?
