### ISSUE TITLE
Race condition in job submission

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#932]
If two jobs share the same prepared application (i.e. same conf-XXX string) then they interfere with one another if they are submitted in parallel.
This is because both jobs use the same temporary `/tmp/username/conf-XXX.tgz` path for uploading to the grid.

In addition, the jobs pollute the `shared/conf-XXX/` directory with their `inputfiles`, so one job ends up with files from the other in addition to its own (this is presumably dangerous if two different jobs have the same prepared application but different input files with the same name (e.g. `job1/blah.txt` and `job2/blah.txt`))

**Comment by rob-c** [comment]
Is the application copied/prepared before being assigned to multiple jobs?
If this is the application is pre-prepared then this is expected behaviour and a minor bug in the RTHandler for GaudiExec.

**Comment by olupton** [comment]
@rob-c yes, I prepare the application and then assign it to multiple jobs (to avoid the very slow re-packaging of the release area). I agree that it looks like a couple of minor bugs (the path under `/tmp/username/__conf-XXX.tgz` should be job-ID dependent, the job `inputfiles` should be added to the `.tgz` directly (or to a uniquely-named temporary directory) instead of being copied into `shared/conf-XXX`)

**Comment by egede** [comment]
@rob-c Where does this copy to /tmp happen? I tried to trace through the code but can't find it.

**Comment by egede** [comment]
OK, so I found a clear bug here.

```
# Create a prepared application
a=prepareGaudiExec('DaVinci','v42r1')
a.options='/home/hep/egede/minimal2.py'
a.prepare()

# Now assign this application to two jobs
j = Job(application=a, backend=Dirac())
j2 = Job(application=a, backend=Dirac())

# Now submit
j.submit()
INFO     submitting job 35
INFO     job 35 status changed to "submitting"
INFO     Job 35's application has already been prepared.
INFO     Uploading file '/tmp/__conf-38d4088a-9aba-4293-b55b-e260ce38fabc.tgz' to 'PIC-USER' as '/lhcb/user/e/egede/GangaInputFile/Job_35/__conf-38d4088a-9aba-4293-b55b-e260ce38fabc.tgz'
:
:

j2.submit()
INFO     submitting job 36
INFO     job 36 status changed to "submitting"
INFO     Job 36's application has already been prepared.
INFO     Uploading file '/tmp/__conf-38d4088a-9aba-4293-b55b-e260ce38fabc.tgz' to 'PIC-USER' as '/lhcb/user/e/egede/GangaInputFile/Job_36/__conf-38d4088a-9aba-4293-b55b-e260ce38fabc.tgz'
:
```
It can be seen here that we attempt to upload the shared file twice to Dirac (and from the same /tmp location). If these two submissions happen at the same time, then it will fail.

The bug is that the information about that the shared file object is already uploaded is kept as a property of the application object (```app.uploadedInput```) where it should instead be a property that is stored in the shared file area. This can prevent that the file is uploaded twice. Now to protect against the race condition, an exclusive lock will need to be placed on the upload operation (in the same way as there is an exclusive lock on the prepare step for GaudiExec).

**Comment by olupton** [comment]
@egede I don't think this covers everything. Clearly if you submit both at the same time then they try to use the same `/tmp/` location. That causes obvious problems that could easily be avoided by putting the job ID in the filename.

The current filename is misleading though, because the uploaded `.tgz` includes the `inputfiles` of the job. Arranging for job 36 to use `/lhcb/user/e/egede/GangaInputFile/Job_35/__conf-38d4088a-9aba-4293-b55b-e260ce38fabc.tgz` is, in general, unsafe.

**Comment by egede** [comment]
@olupton Yes, you are correct that it doesn't cover everything. That the following is allowed

```
a.options = ['file1.py']
a.prepare()
a.options = ['file2.py']
```

is allowed means that there is another bug. Either the last operation should be forbidden or the options file should never go into the shared area. I think the cause of both problems is that only the workflow

```
j.application.prepare()
j.submit()
j2 = j.copy()
j2.submit()
```

is tested. In that case you are protected from the above problem by that the application object is made readonly and that it then is forbidden to change the job options.

**Comment by rob-c** [comment]
Apologies for the delay in replying to this, I've been busy this week.

@egede The copy to temp and upload happens in the prepare step of the master job. There is a dedicated method for doing this from memory.

The fix for this bug needs to solve the following:

 1) The files copied to the tmp dir need to have a unique name for each job not for each prepared application. i.e. the folder should contain the job name not the prepared uuid.
 2) The RTHandler should copy inputfiles to this folder in tmp rather than the shared folder in the shared dir as information not common to the pre-prepared application will confuse things.
 3) We need to consider merging: #701 . Storing the uploaded file here without this will cause problems and increase the need to keep parsing strings into Ganga objects directly. (I was working to see this go, it adds averhead whenever dealing with a string within the schema for _all_ classes and this PR is the only thing which is getting in the way of this!)
 4) We can still store the uploaded information for a submitted job in the application as this is stored once per job object and the application is duplicated and unique upin assignment. It would be nice to move this information to the prepared state but it doesn't apply as the RTHandler intentionally uploads all files for the job in 1 upload to reduce the amount of DIRAC interaction we have.
i.e. There is no need to lock the uploading mechanism as this should be uploading a unique file to the grid and storing unique information within each job object.

 5) (Optional) we could separate the prepared files from those uploaded by the master job but this would require either #701 so we can store multiple files against the prepared state of a job or some other solution so that we can track the extra file somewhere in the schema.

**Comment by egede** [comment]
> We can still store the uploaded information for a submitted job in the application as this is stored once per job object and the application is duplicated and unique upon assignment. It would be nice to move this information to the prepared state but it doesn't apply as the RTHandler intentionally uploads all files for the job in 1 upload to reduce the amount of DIRAC interaction we have.
i.e. There is no need to lock the uploading mechanism as this should be uploading a unique file to the grid and storing unique information within each job object.

@rob-c Does that mean that we do not want the file releasearea tarball uploaded to Dirac to be shared between different jobs with the same prepared application object, but only to be shared between subjobs. That will make things easier, but at the moment the situation is inconsistent.

```
a.prepare()
j1 = Job(application=a)
j2 = Job(application=a)
j1.submit()
j2.submit()
```

results in the releasearea tarball getting uploaded twice. Whereas 

```
a.prepare()
j1 = Job(application=a)
j1.submit()
j2 = j1.copy()
j2.submit()
```

results in only one. The behaviour here needs to be made consistent. To not share the uploaded files between different jobs is obviously easier but it will be less efficient in the usecase from @olupton.
