### ISSUE TITLE
Local() backend doesn't cope with inaccessible LFNs

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#945]
If my job has splitter `SplitByFiles(ignoremissing=False)` and uses the `Dirac()` backend, then if some of the input `DiracFile`s don't have any accessible replicas (because a site is down) I get an error.

If I use the `Local()` backend for the same job then there is no error, the subjobs corresponding to LFNs without accessible replicas are just run with no inputdata, i.e. `__GangaInputData.txt__` is empty.

It would be better if the `Local()` backend threw an error as the `Dirac()` one does.

**Comment by mesmith75** [comment]
So this looks to be rather dependent on the application.
For the old DaVinci application the submission fails for an error thrown by LHCbDataset rather than the splitter itself when submitting locally. In this instance `ignoremissing` doesn't help.
The same is true for GaudiExec.
As noted for Executable the splitter raises a proper exception with the Dirac backend and doesn't for the local, so I guess its a problem in the RTHandler rather than the splitter itself.

**Comment by mesmith75** [comment]
The splitter checks the backend of the job. If it is not Dirac then the splitting algorithm is very simple - I assume because it was designed for local files. I'll add in a method for DiracFiles with a local backend.

**Comment by olupton** [comment]
Hi,
One closely-related thing here: even when the LFNs are accessibly, they are not correctly translated into access URLs in all cases. For example:
```
INFO: read 1 files from __GangaInputData.txt__
Got input files ['file:///storage/gpfs_lhcb/lhcb/user/o/olupton/2017_02/154599/154599514/Lb2SLv17.root']
```
for a file at `CNAF`. To fix this I believe the part of Ganga that writes `__GangaInputData.txt__` needs to request a root or xroot URL. The per-site default protocol is evidently not always one that can be used for remote access.

**Comment by mesmith75** [comment]
Yes, CNAF is a known problem for this. We did debate requesting xroot or root as default but for some reason we decided against it. I'll add it in for the local jobs.
