### ISSUE TITLE
Objects being wiped as soon as they're written

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#96]
I've hit upon a strange bug in the new integration tests. The situation is that I want to add a job to a `JobTree` and then check to see if was added.

In the integration test however, the code seems to be adding the job to the tree and then making it as dirty which prompts a flush to disk. In the process of flushing to disk (using `VStreamer._raw_to_file`) it calls `GangaObject.accept` which requests read access (via `GangaObject._getReadAccess`) which calls `Registry.__safe_read_access` which evaluates `if this_id not in self._loaded_ids` to `True` and so calls `Registry.load` which loads stale information from disk, overwiting the fact that a job was just added.

The registry is question is the one found via `jobtree._impl._getRegistry()` which is the same `getRegistry('jobs').metadata`.

Now, this is only seen in the integration test and so there might just be a slight misconfiguration there but it is 100% reproducible. Have we seen this sort of behaviour before or does anyone (@rob-c) have an idea of what might be causing it?

**Comment by rob-c** [comment]
@milliams As per my email at the start of the year the ```_getReadAccess``` should be transparent and shouldn't perform a registry action if one is currently in progress. (It sounds like a flush to disk is in progress but half way through the object is loaded from disk again)

If the object is being flushed to disk then the Registry shouldn't be evaluating the methods to gain read access as it's a reasonable assumption that you've access if your doing something like writing the object to disk.

```_setDirty``` (or whatever the method in GangaObject is called) doesn't cause an immediate flush to disk due to the dirty count. Is the object correctly added to the registry in the same way that a Job object is added to the standard repo through the ```_auto__init__``` method?

I don't know how the handling of the different repos for one object fully works so I suspect that it's possible some error could be introduced through the Job being in both the registry and not the metadata.

I've not looked at the jobtree since I spend time looking at the registry so I don't want to say too much about how this class works.

**Comment by milliams** [comment]
It turns out that I can indeed reproduce this at the Ganga prompt. The difference is that if you have an existing ~/gangadir then doing:
```python
j = Job()
jobtree.add(j)
jobtree.listjobs()
```
will work correctly but if you completely delete ~/gangadir before running Ganga then the `add()` fails due to the bug I described above. I will look into this a little more.

The JobTree itself is only doing very little, it's perhaps how it interacts with `getRegistry('jobs').metadata` that is causing problems.

**Comment by rob-c** [comment]
If this is failing due to the whole repo has been removed prior to the job being added then this may be due to the initialization of the metadata being delayed I suppose. I've some experience with the code so I'll see if there is anything obvious which could be done to help avert this

**Comment by egede** [comment]
To add a bit of noise, I think that the jobtree is a good candidate for a piece of code to retire in Ganga. The idea dates back all the way to Ganga version 3 and was ported without any consideration about the design. I do not think it does much that you can't do with the "box" where I can store a list of jobs if I like.

**Comment by rob-c** [comment]
@egede I would argue to keep the functionality that this offers as a nice dictionary in the repo metadata to map jobs together. This could be very useful for systems such as Tasks etc in the near future to keep track of what jobs are being used for what.

That being said if this quickly amounts to a lot of work to keep something which is a nicety I'm all for dropping this.
If we dropped this then only the 'prep' registry has a need for a metadata registry attached to itself so I'd be for reducing this functionality to the special case of the prep registry.

**Comment by milliams** [comment]
Thanks @rob-c

It looks like #102 has fixed this bug. I'm still getting some problems with the jobs.metadata registry but I believe these are caused by the test framework rather than anything else.

**Comment by rob-c** [comment]
@milliams  What sort of problems are you seeing with the metadata repo.

#102 Should only have fixes this if the object wasn't being correctly marked as dirty (or somehow wasn't otherwise being flushed) as all of the load commands I removed were preceded by a flush statement which should have put the correct values in the XML. Is the add method in the jobtree marking the jobtree object dirty?

**Comment by milliams** [comment]
The problems I was seeing (and which I have now fixed) were being caused by the JobTree object inside `getRegistry('jobs').metadata` and the one provided by `Ganga.GPI.jobtree` not being the same (and in fact the latter having no _getRegistry() assigned to it). This was caused by a new JobTree being created each time `GangaUnitTest.setUp()` was called but the new object was not being re-exported to the GPI. I've now fixed `GangaUnitTest` to run the bootstrap before every test so this now works.

**Comment by milliams** [comment]
As to the fix to this bug; the jobtree is explicitly marked as dirty at the end of the `add` call. I'm not sure exactly which part of #102 fixed it but it did indeed do the trick.

**Comment by drmarkwslater** [comment]
Just to go back to @egede 's comment - I would much prefer to keep it if possible. If I was doing a significant amount of analysis, I would certainly use it to keep track of jobs and as @rob-c says, I have always planned to integrate it into Tasks as well. If it does prove to be a massive undertaking to keep it working then fair enough but I'd prefer to keep it if possible.

**Comment by drmarkwslater** [comment]
P.S. By 'it' in the previous comment, I was referring to JobTree :)

**Comment by egede** [comment]
@rob-c @drmarkwslater I do not have a problem as such in keeping the job tree. My main point is that I think you would be challenged in finding an active user of it (rather than discussing potential users). But let us keep it at the moment.

**Comment by rob-c** [comment]
If this is fixed I'm not wanting to re-open it.
I think that the dirty value should possibly be set sooner if the method is doing something complex as under some circumstance the object is being flushed (and re-loaded) from some previous state which is what you're seeing but I'm trying to make this as difficult as possible to get into this situation.
It's possible that this may have been fixed by the fact that objects now 'add'ed to the repo are correctly recorded as being fully loaded but I'm dubious it was this that fixed it.

@milliams I'm concerned that is is being fixed in the GangaUnitTest. This is something which should be addressed by the registry class itself correctly during startup/shutdown, if it's not being handled correctly there it should be fixed there because the registry is the object which should (but probably doesn't) have ownership of the metadata.

**Comment by milliams** [comment]
I don't think that this bug was fixed in `GangaUnitTest`. I was seeing the broken behaviour in a plain Ganga interactive session if I wiped my ~/gangadir before starting it. After the changes you made in #102 the behaviour in an interactive session is now correct. This chain of *broken*→#102→*fixed* is independent of `GangaUnitTest` and any changes therein.
