### ISSUE TITLE
Error: XML to-file error for file

### ISSUE THREAD

**Issue by slavkastefkova** [ganga-devs/ganga#997]
Dear ganga experts:
I submitted a job recently (to download JpsiKst tuples for 2016 for a given magnetic polarity with the newest instructions for ganga setup) and this error occured:
INFO     Job 292.434 Running PostProcessor hook
INFO     Job 292.434 Setting Location of LocalFile: *.root
INFO     Job 292.434 Putting File LocalFile: *.root
INFO     resubmitting job 282.311
INFO     job 282 status changed to "submitting"
INFO     resubmitting job 282.311 to Dirac backend
INFO     Contacting DIRAC for job: 292.473
INFO     19.16s taken to download output from DIRAC for Job 292.473
INFO     Job 292.473 Running PostProcessor hook
INFO     Job 292.473 Setting Location of LocalFile: *.root
INFO     Job 292.473 Putting File LocalFile: *.root
INFO     Contacting DIRAC for job: 292.486
INFO     job 282 status changed to "submitted"
ERROR    XML to-file error for file:
out of memory
ERROR    A severe error occurred in the Repository 'jobs': Error of type: <class 'Ganga.Core.GangaRepository.VStreamer.XMLFileError'> on flushing id '292': XMLFileError: to-file error (<type 'exceptions.MemoryError'>:out of memory)
ERROR    If you believe the problem has been solved, type "reactivate()" to re-enable 
INFO     Ganga is now attempting to shut down all running processes accessing the repository in a clean manner
INFO      ... Please be patient! 

I have submitted another job of this kind for other magnetic polarity and it finished with no error.
Now when I type jobs(292) into terminal it will not do anything.
Do you happen to know what is the issue?
Cheers Sally

**Comment by rob-c** [comment]
@slavkastefkova This is related to the machine being under load. Unfortunately Ganga has no protection in place for dealing with this.
Unfortunately the best fix I can suggest is to resubmit the job as it has now likely become corrupt.

It's not clear if this was correctly caught and a write was retried by Ganga again but there appears to be some excessive memory usage due to having loaded many objects from disk. This will potentially get a little better with #917 where the memory usage scales a bit better to the recent ganga changes.

**Comment by slavkastefkova** [comment]
@rob-c Thanks a lot! I will do this.
