### ISSUE TITLE
Problem with configuration system

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#998]
A bug has been introduced in the configuration system which causes out-of-date values to be locked into a users `.gangarc` file. Two instances of this are
   * Starting Ganga as ganga -o'[Logging]Ganga.Lib=DEBUG' will if it at the same time is a release that the user has not used before
   * Values that are changed in `.INI` file are likewise locked into the users .gangarc when the `,gangarc` file is recreated with a new release.

As an example, my `.gangarc` file at Imperial has the values below uncommented

```
load_default_Dirac_backend = False
splitFilesChunks = 5000
datasets = string_dataset_shortcut
associate = {'log': 'TextMerger', 'sim': 'LHCbFileMerger', 'text': 'TextMerger', 'dst': 'LHCbFileMerger', 'txt': 'TextMerger', 'root': 'RootMerger', 'mdst': 'LHCbFileMerger', 'digi': 'LHCbFileMerger'}
creds_poll_rate = 86400
arch = x86_64-slc6-gcc49-opt
location = /cvmfs/lhcb.cern.ch/lib/RootConfig
path = /cvmfs/lhcb.cern.ch/lib/RootConfig/pro/x86_64-slc6-gcc49-opt
pythonhome = /cvmfs/lhcb.cern.ch/lib/GangaConfig/python/pro/x86_64-slc6-gcc49-opt
pythonversion = pro
version = pro
os.environ["PATH"]+=":."
preexecute = exec('import os\nos.chdir(os.environ["TMPDIR"])\nos.environ["PATH"]+=":."\nos.environ["HOME"]=os.environ["TMPDIR"]\nimport shutil,pwd\nshutil.copy(os.path.join("/vols/lhcbdisk05",pwd.getpwuid(os.getuid())[0],".proxy","proxy"),"/tmp/x509up_u%d" % os.getuid())')
submit_str = /home/hep/lhcb/bin/batchproxy; cd %s; qsub -S /usr/bin/python -cwd -V %s %s %s %s
encodeDefaultProxyFileName = False
group = lhcb_user
options = []
submit_with_threads = False
pre_script = ['source /afs/cern.ch/lhcb/software/releases/LBSCRIPTS/prod/InstallArea/scripts/LbLogin.sh', 'source `runpy LbConfiguration.SetupProject --shell=sh --mktemp Ganga`']
queue = hepshort.q
```

The code should be made such that the only uncommented lines written into a new `.gangarc` are those that were uncommented in the file already. A method for cleaning up the mess created in users' `.gangarc` files should also be developed.

**Comment by rob-c** [comment]
Ah, this explains some strange behaviour I've seen when running the tests locally I was seeing some changes persisted somehow. Thought it was something I'd done and wrote it off as my setup being messy or broken.

**Comment by mesmith75** [comment]
I think this was partly introduced by me when I `fixed' the config a while back. I changed it so that the plugin configs are now user values so they would take precedence over the default values.

The problem is that the writing of the config file looks for everything with level 0, i.e. userValues in order to take existing changes from the config file. Of course this also means that stuff defined on the command line will also be taken which is also not wanted (though independent of my change).

I think the best fix is to add another level of gangarc configs to separate them from the default, plugins and user values.

**Comment by mesmith75** [comment]
I guess the other option is to reorder the bootstrap and write the new configuration file before the plugins and user options are loaded.

**Comment by rob-c** [comment]
Adding another level sounds good 👍 
If you do this can you add the option to reset all configs to their default (.gangarc) values?
I've wanted a way to cleanly reset the config parameters between tests so that there is no risk of contanimating a future test due to a past configuration changes and this would do just that I think.

**Comment by mesmith75** [comment]
Sure, although I think there are some functions already there to do that. Perhaps it would be nice to expose them to the GPI.

**Comment by rob-c** [comment]
@mesmith75 it's possible there is something which does this but I couldn't find a switch that said resetToGangarc somewhere or some equivalent.
(Ideally I'd like a way to completely unload and cleanup/destroy the config between tests as this makes sure we've understood how it is constructed in the first place)
